### DISCUSSION TITLE
Having Trouble Detecting an Agent

### DISCUSSION THREAD

**Discussion by drinksomewhiskey** [amir20/dozzle#3580] [Q&A] [answered]
Hi all,

First of all thank you Amir for making such a great tool.

I am having a bit of trouble setting up an agent and having the host detect it. I was wondering if someone could review my docker compose files and let me know if I have something wrong.

The agent docker compose yaml is:
```
version: "3.8"

services:
  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_MODE=agent
      - DOZZLE_HOSTNAME=LittleSurver
    ports:
      - 7007:7007
    restart: unless-stopped
```

The host docker compose yaml is:
```
version: "3.8"

services:
  dozzle:
    image: ghcr.io/amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_HOSTNAME=BigSurver
      - DOZZLE_REMOTE_AGENT=192.168.1.58:7007
    ports:
      - 8080:8080
    restart: unless-stopped
 ```

Both machines are on the same subnet/VLAN on the network and are able to ping one another. This should not be a networking issue. 

Both containers are able to build and run. However, the host is not able to connect to the agent. It shows up but is labeled offline.

I feel like I am missing a label or environment variable. I have read the Wiki, but may not fully understand as I am trying to build my own yamls from the docker run commands listed on the Wiki. As a side note, both machines are a Synolgy NAS.

Any ideas? Thank you in advance!

**Comment by amir20** [comment]
@drinksomewhiskey you should check your UI logs. The error would be there. You can also use the helper

```
$ docker run amir20/dozzle:latest agent-test [ip]:7007
```

You most likely have a firewall or something blocking it.

**Reply by drinksomewhiskey** [reply]
Thanks for the quick reply @amir20. For some background, both of the systems are a Synology NAS. 

I read the logs and was able to see:

```
level=
warn
error=
rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"
endpoint=
192.168.1.58:7007
time=
2025-01-27T08:08:08Z
message=
error fetching host info for agent
level=
warn
error=
rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"
time=
2025-01-27T08:08:08Z
message=
error listing containers
```
```
level=
warn
error=
rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"
endpoint=
192.168.1.58:7007
time=
2025-01-27T08:08:08Z
message=
error fetching host info for agent
level=
warn
error=
rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"
time=
2025-01-27T08:08:08Z
message=
error listing containers
```

It seems to be an authentication issue, but I am not sure what to try. It should not be a firewall issue as Portainer (running on the same machine as the Dozzle host) is able to connect to the other machine (running the Dozzle agent). Both machines are on the same subnet/VLAN. There are no firewall rules that would block access. I do not have Synology firewall rules running either.

Did my docker compose yamls look ok? Given that these are running on a Synology, docker run does not really work. I had to set things up via docker compose.

**Reply by amir20** [reply]
I have never seen `transport: authentication handshake failed: EOF` before. You can try the above command and test locally to see if it makes a difference. This isn't an error I have seen error so I am not sure.

**Reply by drinksomewhiskey** [reply]
In reading the dozzle agent container logs and I see the following:
```
{
  "time": "2025-01-28T03:37:27Z",
  "level": "warning",
  "msg": "Unexpected environment variable DOZZLE_AGENT_MODE"
}
```
I have tried environment variables ```DOZZLE_MODE=agent``` as well as ```DOZZLE_AGENT_MODE=true```. Neither one seems to work. How can I specify agent mode via docker compose? The Wiki states that ```DOZZLE_MODE``` defaults to server. Is there a way to specify agent mode?

**Reply by amir20** [reply]
Ah. I didn't see that before. You need to pass a sub command. It's documented at https://dozzle.dev/guide/agent#how-to-create-an-agent

**Reply by drinksomewhiskey** [reply]
> Ah. I didn't see that before. You need to pass a sub command. It's documented at https://dozzle.dev/guide/agent#how-to-create-an-agent

I tried this. The container does not build using ```command: agent```. The log states ```error: invalid subcommand: agent```. This is why I was trying to use ```DOZZLE_MODE=agent``` and ```DOZZLE_AGENT_MODE=true``` environment variables instead. This is the exact compose for with the agent command that I am running, which does not build:

```
version: "3.8"

services:
  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: agent
    environment:
      - DOZZLE_HOSTNAME=LittleSurver
    ports:
      - 7007:7007
    restart: unless-stopped
```
