### DISCUSSION TITLE
Logging separate files on disk to stdout and stderr

### DISCUSSION THREAD

**Discussion by FoxxMD** [amir20/dozzle#3608] [Show and tell]
Building on [Logging Files on Disk](https://dozzle.dev/guide/log-files-on-disk) from the docs -- I wanted to output nginx logs, which logs separately to `access.log` and `error.log`, respectively to stdout and stderr. But the example in the docs wasn't enough to figure this out.

Here's how to do this using docker-compose

```yaml
  tail-logs:
    image: alpine
    volumes:
      - /host/path/to/nginx:/var/log/nginx:ro
    command: >
      sh -c "tail -f /var/log/nginx/access.log &
             tail -f /var/log/nginx/error.log >&2"
    network_mode: none
    restart: unless-stopped
```

The first log will be output to stdout, the second to stderr
