### DISCUSSION TITLE
Dozzle K8s is here! See here for instructions and provide feedback.

### DISCUSSION THREAD

**Discussion by amir20** [amir20/dozzle#3614] [Announcements]
Hi all,

While looking at the survey results, I noticed a few people rely on K8s support heavily. I am currently working on k8s support and it is almost complete. I still need to add documentation. But I am hoping I could get a couple volunteers who would be interested in testing Dozzle in their k8s cluster. 

Implementation for Dozzle in k8s is a lot more performant since stats for containers is returned across all containers. Additionally, k8s services are stable so agents are not required. 

I will be adding docs soon. For those who are interested, I will provide directions. In the future, I hope to release a helm package.

**Comment by troke12** [comment]
I have some cluster k8s, can't wait for that and go test it!

**Reply by amir20** [reply]
@troke12 could you try it? I put the config below.

**Reply by troke12** [reply]
Ah sure, i'll test it for tomorow

**Comment by amir20** [comment]
Hello,

I have been excited about adding k8s support. In the survey, a few people expressed, but not a lot. I thought it would be a good addition and apparently, judging from the ❤️ it seems like people might like. 

Here is what you need to test Dozzle with k8s.  Dozzle `master` branch has k8s support with `DOZZLE_MODE=k8s`. 

## Installing

This is the file I did to spin up Dozzle

```yaml
# rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-viewer
---
# clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-viewer-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
# clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-viewer-binding
subjects:
  - kind: ServiceAccount
    name: pod-viewer
    namespace: default
roleRef:
  kind: ClusterRole
  name: pod-viewer-role
  apiGroup: rbac.authorization.k8s.io
---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dozzle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dozzle
  template:
    metadata:
      labels:
        app: dozzle
    spec:
      serviceAccountName: pod-viewer
      containers:
        - name: dozzle
          image: amir20/dozzle:master
          ports:
            - containerPort: 8080
          env:
            - name: DOZZLE_MODE
              value: "k8s"
            - name: DOZZLE_LEVEL
              value: "debug"
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dozzle-service
spec:
  type: ClusterIP
  selector:
    app: dozzle
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
```

Install using `kubectl apply -f dozzle.yml`

Dozzle for K8s has turned out to be very performant because the API for k8s are more efficient. 

## Requirements
1. To collect metrics, [metrics server](https://github.com/kubernetes-sigs/metrics-server) API is required.  In the future, I plan to make this optional where if it is not installed, it would just fallback to no stats. Metrics Server can be installed with `kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml`
2. rbac permission to pods and metrics is required to fetch and view logs. See above for example. 

## What doesn't work?
1. K8s doesn't currently support filters or user filters. I plan to come back to this later. 
2. There maybe bugs as my k8s cluster is very simple. 
3. The UI might still say Docker compose or services. I haven't updated a lot of the UI to reflect k8s

Please test this and provide feedback on this discussion. I am looking for a few folks who can install and learn from their experience. I also want to make sure Dozzle remains light so if you see high memory or CPU usage then let me know. 

Thanks 🎉🚀
