### DISCUSSION TITLE
Trouble to connect to more than one agent

### DISCUSSION THREAD

**Discussion by JueFri** [amir20/dozzle#3753] [Q&A] [answered]
First of all thank you Amir for making such a great tool.

I am not able to connect to more than one agent. 

On the dozzle host i am only able to connect to the first agent in the list of the DOZZLE_REMOTE_AGENT environment variable. The second one is light grey and not selectable.

Maybe someone could review my docker compose files and tell me what i make wrong.   

The host docker compose yaml is:

```
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      - DOZZLE_ENABLE_SHELL=true
      - DOZZLE_REMOTE_AGENT=192.168.2.46:7007, 192.168.2.53:7007
```

Docker log

```
{"level":"info","version":"v8.12.3","time":"2025-04-03T15:20:51Z","message":"Dozzle version v8.12.3"}
{"level":"warn","version":"v8.12.3","error":"rpc error: code = Unavailable desc = name resolver error: produced zero addresses","endpoint":" 192.168.2.53:7007","time":"2025-04-03T15:20:51Z","message":"error fetching host info for agent"}
{"level":"info","version":"v8.12.3","clients":2,"time":"2025-04-03T15:20:51Z","message":"Connected to Docker"}
{"level":"info","version":"v8.12.3","time":"2025-04-03T15:20:51Z","message":"Accepting connections on :8080"}
{"level":"warn","version":"v8.12.3","error":"rpc error: code = Unavailable desc = name resolver error: produced zero addresses","endpoint":" 192.168.2.53:7007","time":"2025-04-03T15:31:36Z","message":"error fetching host info for agent"}
{"level":"warn","version":"v8.12.3","error":"rpc error: code = Unavailable desc = name resolver error: produced zero addresses","time":"2025-04-03T15:31:36Z","message":"error listing containers"}
{"level":"warn","version":"v8.12.3","error":"rpc error: code = Unavailable desc = name resolver error: produced zero addresses","endpoint":" 192.168.2.53:7007","time":"2025-04-03T15:31:42Z","message":"error fetching host info for agent"}
{"level":"warn","version":"v8.12.3","error":"rpc error: code = Unavailable desc = name resolver error: produced zero addresses","time":"2025-04-03T15:31:42Z","message":"error while listing containers"}
{"level":"warn","version":"v8.12.3","error":"rpc error: code = Unavailable desc = name resolver error: produced zero addresses","endpoint":" 192.168.2.53:7007","time":"2025-04-03T15:31:47Z","message":"error fetching host info for agent"}
{"level":"warn","version":"v8.12.3","error":"rpc error: code = Unavailable desc = name resolver error: produced zero addresses","time":"2025-04-03T15:31:47Z","message":"error while listing containers"}
```

The agent_1 192.168.2.46 docker compose yaml is:

```
services:
  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle_agent
    command: agent
    environment:
      - DOZZLE_HOSTNAME=ittools
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
```

Docker log

```
{"level":"info","version":"v8.12.3","time":"2025-04-03T08:53:13Z","message":"Dozzle agent version v8.12.3"}
{"level":"info","version":"v8.12.3","time":"2025-04-03T08:53:13Z","message":"Agent listening on [::]:7007"}
```

The agent_2  192.168.2.53 docker compose yaml is:

```
services:
  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle_agent
    command: agent
    environment:
      - DOZZLE_HOSTNAME=adguard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007

```

Docker log

```
{"level":"info","version":"v8.12.3","time":"2025-04-03T08:51:07Z","message":"Dozzle agent version v8.12.3"}
{"level":"info","version":"v8.12.3","time":"2025-04-03T08:51:07Z","message":"Agent listening on [::]:7007"}
```
