### DISCUSSION TITLE
Support for Openshift cluster

### DISCUSSION THREAD

**Discussion by Wisw** [amir20/dozzle#3756] [General]
### Describe the feature you would like to see

I just love Dozzle ! The simplicity and intuitive manner it has been so far. Yet with finesse options it present to the users.

I want to use dozzle onto an OCP or Openshift cluster. I'm not sure if installing kubernetes metrics api will work in OCP. I request if that can be done as well, would be great.

### Describe how you would like to see this feature implemented

Perhaps using native metrics API available over OCP. I'm not sure if its same.

**Comment by amir20** [comment]
Hello,

Based on my preliminary research, it should work in OpenShift. I believe OpenShift uses the Kubernetes metrics API out of the box. Since I don't run OpenShift personally, you'll need to try it and see what works.

Dozzle provides a solid abstraction between container providers and other orchestration platforms. If something doesn't work, it should be easy to override specific functionality.

> Perhaps using native metrics API available over OCP. I'm not sure if its same.


As far as I know, there is no native metrics API.

**Reply by amir20** [reply]
@Wisw did you ever try it?

**Reply by Wisw** [reply]
Hello @amir20 ,

I have tried it over weekend and this worked as fine as anywhere else.

I have checked before deploying reg. the native metrics API. Its the same Kubernetes metrics API being used in latest OCP 4.x

I had to allow user (serviceAccount) via SCC to make it work in my case for the pod to get scheduled. Thanks again.

**Reply by amir20** [reply]
Great! If you did something specific to make it work then please do update the documentation.

**Reply by Wisw** [reply]
Here's what worked for in my case:

```
# deployment.spec.template.spec part
      containers:
        - name: dozzle
          image: amir20/dozzle:latest
          ports:
            - containerPort: 8080
          env:
            - name: DOZZLE_MODE
              value: "k8s"
            - name: DOZZLE_BASE
              value: "/logs"
          securityContext:
            allowPrivilegeEscalation: true
```

And in order to get the security context allowed for a pod & thus a container via admission controller, I had to create below as a custom SCC:

```
allowPrivilegeEscalation: true
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: custom-scc
priority: null
users:
- system:serviceaccount:<namespace_name_or_project>:pod-viewer

```
