### DISCUSSION TITLE
Need help using dozzle in agent mode

### DISCUSSION THREAD

**Discussion by xd003** [amir20/dozzle#3810] [Q&A] [answered]
i have multiple vps server, say vps A & B. I have deployed dozzle WebUI  on vps A which i am gonna access using my domain with reverse proxy hence i have skipped exposing the port 8080.
```
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    environment:
    - DOZZLE_REMOTE_AGENT={??}
 ```

Now after i deploy dozzle agent in vps B, is it possible to connect this agent to webUI on vps A without exposing the port 7007 ?
