### DISCUSSION TITLE
Dozzle not loading behind caddy

### DISCUSSION THREAD

**Discussion by rishikanthc** [amir20/dozzle#3954] [General]
### 🔍 Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

v8.12.21

### ✅ Command used to run Dozzle

Hi,
I'm also having trouble getting dozzle to work behind caddy. Below is my caddy labels i use on my dozzle docker container:
```yaml
labels:
      caddy: https://doz.example.com
      # # caddy.import: tinyauth_forwarder *
      caddy.reverse_proxy.flush_interval: "-1"
      caddy.reverse_proxy: "{{upstreams 8080}}"
```

I'm using [caddy-docker-proxy](https://github.com/lucaslorentz/caddy-docker-proxy) for caddy.. Nothing loads and I get this popup:
"Dozzle UI timed out while connecting to API. Please check network connection and try again." And after a long wait, it loads the available containers and when you click on one the logs don't load either..
Wondering what I'm doing wrong.. any help would be appreciated. 

### 🐛 Describe the bug / provide steps to reproduce it

Here's the full docker-compose i'm using:
```yaml
# Run with docker compose up -d
services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      caddy: https://doz.example.com
      
      # # caddy.import: tinyauth_forwarder *
      caddy.reverse_proxy.flush_interval: "-1"
      # caddy.@notSSE.not.path: "/api/events/stream* api/logs/stream*"
      caddy.reverse_proxy: "{{upstreams 8080}}"

    networks:
      - caddy_net

    # ports:
    #   - 8080:8080
    environment:
      DOZZLE_LEVEL: debug
      # Uncomment to enable container actions (stop, start, restart). See https://dozzle.dev/guide/actions
      # - DOZZLE_ENABLE_ACTIONS=true
      #
      # Uncomment to allow access to container shells. See https://dozzle.dev/guide/shell
      # - DOZZLE_ENABLE_SHELL=true
      #
      # Uncomment to enable authentication. See https://dozzle.dev/guide/authentication
      # - DOZZLE_AUTH_PROVIDER=simple


networks:
  caddy_net:
    external: true
```

### 💻 Environment

Running on a clean debian install.. I don't have SSH access to the machine right now but I can follow up with details if needed

### 📜 Dozzle logs are required for debugging purposes. You may need to enable debug mode. See https://dozzle.dev/guide/debugging.

dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:00:01Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:00:01Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /ferretdb ping","id":"5de01211a617","time":"2025-06-06T21:00:04Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /ferretdb ping","id":"5de01211a617","time":"2025-06-06T21:00:04Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /ferretdb ping","id":"5de01211a617","time":"2025-06-06T21:00:04Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /ferretdb ping","id":"5de01211a617","time":"2025-06-06T21:00:04Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"5de01211a617","time":"2025-06-06T21:00:04Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"5de01211a617","time":"2025-06-06T21:00:04Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:05Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:05Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:05Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:05Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:05Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:05Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:11Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:11Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:11Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:11Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:00:11Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:00:11Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:15Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:15Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:15Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:15Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:16Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:16Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:21Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:21Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:21Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:21Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:00:21Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:00:21Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:26Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:26Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:26Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:26Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:26Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:26Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:31Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:31Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:31Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:31Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:00:31Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:00:31Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:36Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:36Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:36Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:36Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:36Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:36Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:41Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:41Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:41Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:41Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:00:41Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:00:41Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:46Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:46Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:46Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:46Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:46Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:46Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:51Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:51Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:51Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:00:51Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:00:51Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:00:51Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:56Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:56Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:56Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:56Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:56Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"0ae4bdfa1d21","time":"2025-06-06T21:00:56Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:01:01Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:01:01Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:01:01Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:01:01Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:01:01Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:01:01Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /ferretdb ping","id":"5de01211a617","time":"2025-06-06T21:01:04Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /ferretdb ping","id":"5de01211a617","time":"2025-06-06T21:01:04Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /ferretdb ping","id":"5de01211a617","time":"2025-06-06T21:01:04Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /ferretdb ping","id":"5de01211a617","time":"2025-06-06T21:01:04Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"5de01211a617","time":"2025-06-06T21:01:04Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"5de01211a617","time":"2025-06-06T21:01:04Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:01:06Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:01:06Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:01:06Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c node ./healthcheck.js","id":"0ae4bdfa1d21","time":"2025-06-06T21:01:06Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"0ae4bdfa1d21","time":"2025-06-06T21:01:06Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"0ae4bdfa1d21","time":"2025-06-06T21:01:06Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:01:11Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_create: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:01:11Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:01:11Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_start: /bin/sh -c pg_isready -U postgres -d planka","id":"15015d46bf0c","time":"2025-06-06T21:01:11Z","message":"container event from store"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:01:11Z","message":"received container event"}
dozzle-1  | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"15015d46bf0c","time":"2025-06-06T21:01:11Z","message":"container event from store"}

**Comment by amir20** [comment]
I am not very familiar with caddy proxy. The error you are getting suggests the browser is never able to get an update. You may need to disable caching. Dozzle uses websockets AND server send events. 

I won't have time to test it for you. Last time I tested locally with Caddy it worked. 

Going to move this to discussion. Maybe someone else can help....

**Comment by Mertico** [comment]
The same error with config 
<img width="1512" alt="Screenshot 2025-06-08 at 17 35 10" src="https://github.com/user-attachments/assets/0de6cb13-ed6e-47e9-b10b-48a3327328c5" />

```
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    networks:
      - internal-network
      - swarm-network
    ports:
      - 8080:8080
    environment:
      - DOZZLE_MODE=swarm
      - DOZZLE_NO_ANALYTICS
      - DOZZLE_AUTH_PROVIDER=none
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_LEVEL=debug
      - DOZZLE_ENABLE_SHELL=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global

```

**Reply by Mertico** [reply]
```
dozzle      | {"level":"debug","version":"v8.12.21","containers":10,"time":"2025-06-08T15:06:35Z","message":"finished initializing container store"}
dozzle      | {"level":"debug","version":"v8.12.21","host":"raspberrypi","time":"2025-06-08T15:06:35Z","message":"Fetching host"}
dozzle      | {"level":"debug","version":"v8.12.21","event":"exec_create: mc ready local","id":"03a1eb42bf90","time":"2025-06-08T15:06:35Z","message":"received container event"}
dozzle      | {"level":"debug","version":"v8.12.21","event":"exec_start: mc ready local","id":"03a1eb42bf90","time":"2025-06-08T15:06:35Z","message":"received container event"}
dozzle      | {"level":"debug","version":"v8.12.21","event":"exec_create: mc ready local","id":"03a1eb42bf90","time":"2025-06-08T15:06:35Z","message":"received container event"}
dozzle      | {"level":"debug","version":"v8.12.21","event":"exec_start: mc ready local","id":"03a1eb42bf90","time":"2025-06-08T15:06:35Z","message":"received container event"}
dozzle      | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"03a1eb42bf90","time":"2025-06-08T15:06:35Z","message":"received container event"}
dozzle      | {"level":"debug","version":"v8.12.21","event":"exec_die","id":"03a1eb42bf90","time":"2025-06-08T15:06:35Z","message":"received container event"}
dozzle      | {"level":"debug","version":"v8.12.21","labels":{},"host":"raspberrypi","time":"2025-06-08T15:06:35Z","message":"Listing containers"}
dozzle      | {"level":"fatal","version":"v8.12.21","error":"lookup tasks. on 127.0.0.11:53: no such host","time":"2025-06-08T15:06:35Z","message":"error looking up swarm service tasks"}
dozzle exited with code 1
```


Just crush after send page http://100.90.201.21:8080 or api curl -vvv 'http://100.90.201.21:8080/api/events/stream'
<img width="1059" alt="Screenshot 2025-06-08 at 18 10 15" src="https://github.com/user-attachments/assets/564949c8-9e60-44bc-9bf2-b056a6b2c6b6" />

**Reply by amir20** [reply]
This is a different error

> {"level":"fatal","version":"v8.12.21","error":"lookup tasks. on 127.0.0.11:53: no such host","time":"2025-06-08T15:06:35Z","message":"error looking up swarm service tasks"}

That sounds like an error with your swarm. Dozzle tries to use DNS to discover other nodes. This is a DNS error. I've never seen this before. Sounds like a configuration error.

**Comment by leosuncin** [comment]
After killing some neurons, and using this https://github.com/linuxserver/reverse-proxy-confs/blob/master/dozzle.subfolder.conf.sample as a reference, I found out to disable `compression` and set `flush_interval` to -1 do the trick:

```yaml
name: Dozzle

services:
  dozzle:
    restart: unless-stopped
    image: ghcr.io/amir20/dozzle:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - caddy
    environment:
      # Caddy Security https://github.com/greenpau/caddy-security
      # - DOZZLE_AUTH_PROVIDER=forward-proxy
      # - DOZZLE_AUTH_HEADER_USER=X-Token-User-Email
      # - DOZZLE_AUTH_HEADER_EMAIL=X-Token-User-Email
      # - DOZZLE_AUTH_HEADER_NAME=X-Token-User-Name
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
      - DOZZLE_LEVEL=info
      - DOZZLE_FILTER="status=running"
    security_opt:
      - no-new-privileges=true
    healthcheck:
      test:
        - CMD
        - /dozzle
        - healthcheck
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    labels:
      caddy: dozzle.example.org
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.reverse_proxy.transport: http
      caddy.reverse_proxy.transport.compression: off
      caddy.reverse_proxy.flush_interval: -1

networks:
  caddy:
    external: true
```
