### DISCUSSION TITLE
with a socket proxy on a Swarm

### DISCUSSION THREAD

**Discussion by IGitYou** [amir20/dozzle#3983] [Q&A] [answered]
Hello all. 

I just tried to stand up a dozzle interest in my dev env in hopes to make my life a little easier. 

Seeing it uses the socket to connect and I just went through a round of hardening on my box, I do not expose the socket to any service anymore except a proxy. 

I was able to get this somewhat working using your documentation, but was hoping there was a way for me to tell Dozzle to only use a socket proxy running locally on that node. This would permit local access to the local socket. 

Currently it appears to query and let the swarm LB determine which container it will land on. I do not get full representation of the cluster and have some other behaviors that I am betting are related. 

I played with this yesterday and could not get it working. Wondering if anyone has a working config like this involving both a socket proxy and a Swarm cluster in Docker. 

thanks for any insights.

**Comment by amir20** [comment]
> I was able to get this somewhat working using your documentation, but was hoping there was a way for me to tell Dozzle to only use a socket proxy running locally on that node. This would permit local access to the local socket. 

I am not sure what this means. Just set up a proxy and point Dozzle to it as documented. 

> Currently it appears to query and let the swarm LB determine which container it will land on. I do not get full representation of the cluster and have some other behaviors that I am betting are related.

What is _it_? Dozzle on swarm needs to get deployed on every node in swarm. They all communicate together to accurately represent all the containers in the cluster. Dozzle doesn't use swarm API as it is unstable and doesn't work. 

I would recommend first setting up Dozzle without any proxies and then moving to proxy. 

If there are any bugs without proxy then I think it's worth opening issues so I can see if they are really bugs. If something doesn't work with a proxy, then you'll need to investigate yourself as it is outside of my scope to support all proxy types out there. 

If something is missing in the docs, then a PR would be appreciated. 

Finally, when asking for help, it would be best to share all your configuration.

**Reply by IGitYou** [reply]
Please pardon teh ambiguity. 

I believe the issue is that in the model described (global service deployed to each node) the assumption is the service per node is connecting to the local native socket and pulling all the data it needs from that local docker node. 

`I am not sure what this means. Just set up a proxy and point Dozzle to it as documented.`

If I have a 3 node cluster and deploy a socket on one node, all traffic may reach the proxy, but that proxy may not have the full stack of info from all docker nodes, as it is not present on all nodes. 

I considered trying to deploy the socket globally too, but even then I can see that Docker's name resolution is loadbalancing the requests and the local instance is not always chosen. 

I hope this helps and thanks.

**Reply by amir20** [reply]
I think I am not understanding this.

> If I have a 3 node cluster and deploy a socket on one node, all traffic may reach the proxy, but that proxy may not have the full stack of info from all docker nodes, as it is not present on all nodes.

That won't work. If you want to use swarm, then the proxy needs to be deployed on every single node. 

Your options are: 

1. Deploy proxy and Dozzle Swarm on every single node and point to localhost proxy 
2. Don't use Swarm and just good ol' single UI instance with a different proxies 

> I considered trying to deploy the socket globally too, but even then I can see that Docker's name resolution is loadbalancing the requests and the local instance is not always chosen.

Not sure what this means. 

Personally, I think you are over complicating it. I get people want to use proxies, but these layers of wrappers aren't natively supported by Docker. I don't use proxies a lot because I see them as additional systems that might fail. As suggested earlier, use without proxy. If it all works, then start adding new components.

**Reply by IGitYou** [reply]
Thanks for your reply.

`Deploy proxy and Dozzle Swarm on every single node and point to localhost proxy`

This is exactly what I tried but specifying localhost does not work (maybe it goes to the dozzle local container?) and I have not figured out a way to explicitly ensure that Dozzle uses the socket proxy that is local. 

Thanks for the additional feedback. Outside of the bit on overcomplicating it, it is just not applciable to what I am currently seeking. I am sure it does work directly with the socket but that is not what I am seeking currently. Conversely, Portainer runs and gets logs through the non-global socket proxy as far as I have seen since implemented... as well as everything else I see Dozzle doing, so I believe it to be possible. Just trying to figure out the correct config to make her sing.

**Reply by amir20** [reply]
> This is exactly what I tried but specifying localhost does not work (maybe it goes to the dozzle local container?) and I have not figured out a way to explicitly ensure that Dozzle uses the socket proxy that is local.

Can you share config? Because that should work. 

Edit: 

> maybe it goes to the dozzle local container

Yes that's what it would do. But I assume you were able to point to the proxy.

**Reply by IGitYou** [reply]
I will try to make a basic example config and get it up here. THanks 

`Yes that's what it would do. But I assume you were able to point to the proxy.`
I can point it to the proxy by service name and network alias. Doing so does not always point it to the local instance of the service. using localhost is not working because I think it is looking inside the container for the proxy... which is naturally wrong. 

This is the issue. I believe it goes to the Swarm DNS and does a lookup and the swarm determines which of the services IPs it is going to get you. Specifying a network translatable address does not assure the local instance will work and the swarm directions assume it is using the direct socket. The question: How to configure a socket proxy to a local socket proxy instance to emulate the desired swarm config of this service. 

I tried to change the service name to append a NodeHostName or whatever to it and have not been successful. I am not great at most I do (at first), but research shows my approach may not be supported (server templates in swarm service compose files). 

If localhost were translated as the local instance of the container I do not think I would have an issue. I think ContainerID:Port would work because I can see this as the DNS alias. This is my attempted config.

**Reply by amir20** [reply]
I see your problem now. I think you have to use network host mode and point to `host.docker.internal`. To be honest, I do not know either. I don't have a lot of time to test things. I'll wait until you provide an example.  

I hope we can figure this out to document for other people. I bet with ChatGPT there is a way to get something working. :P

**Reply by amir20** [reply, marked as answer]
I did some reading last night. I am afraid this is not possible. Swarm services can only communicate with other services. You can use `network_mode: host` but I wouldn't recommend it. 

Your best option is to set up each node manually with one central UI. 

I have updated the documentation to reflect this.

**Reply by IGitYou** [reply]
host networking will not work as it is not a swarm thing 
You can do macvlan networking and you may get that to work... but then you end up tring to assing static IPs and stuff gets messy from them on out. 

I feel like if I could append the cluster node name to each service I could  do it. 

I also feel like each is uniquely addressible by the containers DNS addressible name... but building that out would involve the nodeID and the containerID . I am failing at even the nodeName. 

THanks for your feedback. 

I read that localhost is specially translated by dozzle in the docs. I did not read any details at what that meant specificlly. I was hoping it did some magic. 

I know service discovery based on port should be possible. It is with other services I run. Perhaps there is an opportunity to be able to resolve 127.0.0.1:2037 (or whatever teh socket's port is) and have it do local port discovery on all networks . I question if that would not work. 

I was just hoping I was not a pioneer in this issue. 

Thanks again. 


Your answer is not accurate though because host networking cannot be used in a swarm

**Comment by amir20** [comment]
@IGitYou 

According to ChatGPT. These are your options: 

You're absolutely correct! When a container connects to `localhost`, it's connecting to the container's own network namespace, not the host. Let me clarify the proper approaches:

## **Host Network Mode** (Corrected)

When using `host` network mode, the container shares the host's network namespace, so `localhost` actually works:

```yaml
version: '3.8'
services:
  proxy:
    image: your-proxy-image
    network_mode: host  # Shares host network
    deploy:
      mode: global
  
  app:
    image: your-app-image
    network_mode: host  # Also shares host network
    environment:
      - PROXY_URL=http://localhost:8080  # This works because both use host network
    deploy:
      mode: global
```

## **Published Ports** (Most Common Solution)

For containers with default bridge/overlay networks, you need to connect to the host IP:

```yaml
version: '3.8'
services:
  proxy:
    image: your-proxy-image
    ports:
      - "8080:80"  # Published to host
    deploy:
      mode: global
  
  app:
    image: your-app-image
    environment:
      # Connect to host IP, not localhost
      - PROXY_URL=http://host.docker.internal:8080  # Docker Desktop
      # OR discover host IP dynamically (see below)
    deploy:
      mode: global
```


## **Using Docker's Special DNS Names**

In newer Docker versions, you can use special hostnames:

```yaml
version: '3.8'
services:
  proxy:
    image: your-proxy-image
    ports:
      - "8080:80"
    deploy:
      mode: global
  
  app:
    image: your-app-image
    environment:
      # These work in some Docker environments
      - PROXY_URL=http://host.docker.internal:8080  # Docker Desktop
      # OR
      - PROXY_URL=http://gateway.docker.internal:8080
    deploy:
      mode: global
```


Unfortunately, I don't think any of these are great ideas. It seems that swarm mode with proxy is not a good option. This isn't a problem with Dozzle so there isn't anything I can do.
