### ISSUE TITLE
Support for TLS docker sockets over TCP

### ISSUE THREAD

**Issue by samrocketman** [amir20/dozzle#1]
Just creating a feature request.  It would be nice to run dozzle off-host (or not have to mount the docker unix socket).  Docker can be configured with mutual TLS authentication for the client and daemon.

See also 
https://docs.docker.com/engine/security/https/

I also have certificate authority management scripts for this purpose 
https://github.com/samrocketman/my_internal_ca

**Comment by amir20** [comment]
Thanks @samrocketman . I'll see how it is to do this. Do you know of any other similar tools that do the same thing by the way? I thought mounting docker unix socket file is so common that most people would be fine with it. But if there are other examples then I can see how they did it.

**Comment by samrocketman** [comment]
Whenever I’ve done this it’s be configuring the `docker` command client to talk to a remote docker.  There’s also a Java implementation which I have used in the past in two similar Jenkins plugins.

1. https://github.com/KostyaSha/yet-another-docker-plugin
2. https://github.com/jenkinsci/docker-plugin

If I find direct code examples I’ll link them.

**Comment by amir20** [comment]
Thanks @samrocketman. I was playing around with watchtower and it supports some SSL stuff. I think I'll try to match same feature. What do you think?

**Comment by samrocketman** [comment]
To be honest I don’t plan to use dozzle myself since for home use I run containers using docker-compose and systemd.

So if you don’t find yourself in dire need of this feature then put a pin in this for yourself later to try out.

Just being clear so you don’t rush yourself on my part.  I was looking through your source and docs; and I notice this was missing which, if I were to use dozzle, I would want it.

Feel free to keep this open as an enhancement (or close if you don’t think you want it at this time).  Just wanted to contribute the issue as food for thought and be clear about my own intentions.

**Comment by amir20** [comment]
That's fair @samrocketman. I'll leave this ticket open. 

I also use this mostly for my side projects. I currently have a few projects running in swarm/compose in DigitalOcean. Sometimes I push updates and then go on my iPad later on. I generally check on my laptop if I broke anything. It has worked pretty well.  I didn't feel paying $7/month for papertrail and that's why I made this. As you have seen the code, it's pretty simple. 

Right now I am working on making the UI better. Some of that is being discussed in #2 if you are interested. 

If others want TLS then I can add it.

**Comment by amir20** [comment]
I am going to close this since not many people have asked for this feature.

**Comment by samrocketman** [comment]
Sounds good. Thanks for considering anyways :-)

**Comment by jwmarshall** [comment]
For what its worth I was able to get dozzle to support TLS over TCP without any changes, though perhaps there have been updates since this thread to support this. Now mounting the certificates like this is not the most secure depending on your system access levels, as anyone with docker access could easily mount them. In my case I'm only running the dozzle on the same host that Im monitoring, so anyone that could launch a container already has access to the certificates.

Hope this helps someone.

```
version: '3.4'
services:
  dozzle:
    image: amir20/dozzle:latest
    logging:
      driver: json-file
      options:
        max-size: "128m"
        max-file: "3"
    ports:
    - "8080/tcp"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 120s
    healthcheck:
        start_period: 60s
    extra_hosts:
    - "docker-hostname:172.18.0.1"
    environment:
    - DOCKER_CERT_PATH=/run/secrets
    - DOCKER_TLS_VERIFY=true
    - DOCKER_HOST=tcp://docker-hostname:2376
    #- DOZZLE_TAILSIZE=100
    #- DOZZLE_FILTER=
    secrets:
    - ca.pem
    - cert.pem
    - key.pem

secrets:
   ca.pem:
      file: /etc/docker/certs/ca.pem
   cert.pem:
      file: /etc/docker/certs/cert.pem
   key.pem:
      file: /etc/docker/certs/key.pem
```
