### ISSUE TITLE
Unable to update to 3.3.0/3.3.1

### ISSUE THREAD

**Issue by steakhutzeee** [amir20/dozzle#1096]
**Describe the bug**
Running Dozzle 3.2.3 in docker container. Image is amir20/dozzle:latest.
Pulling the new 3.3.0/3.3.1 docker output that i'm up to date.

**To Reproduce**
My docker-compose file:

```
version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4040:8080
    restart: unless-stopped
networks:
    default:
      external:
        name: my-net
```
**Desktop (please complete the following information):**
 - OS: OMV5
 - Docker version:
```
 Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:19:30 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:17:16 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
