### ISSUE TITLE
Reverse proxy in custom bridge network not working

### ISSUE THREAD

**Issue by landcraft** [amir20/dozzle#1102]
**Describe the bug**
I am unable to reverse proxy using hostname when dozzle is on the same custom bridge as nginx

**To Reproduce**
1. docker-compose dozzle as instructed & proxy_pass HTTP://dozzle:8080;
2. restart nginx
3. browse to dozzle.mydomain.com
4. nginx landing page instead of dozzle page

**Expected behavior**
Dozzle page should load. 
BTW, when I change the proxy_pass to HTTP://<Docker Host IP>:<mapped port>, it works

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows or Mac Os]
 - Docker version [e.g. `docker version`'s output]
 - Browser & version: chrome
 - Version: latest

**If applicable include logs with `--level debug` and browser logs**

**Comment by amir20** [comment]
Hey @landcraft isn't this related to nginx configuration? I don't know what Dozzle could be doing that could impact this.

**Comment by landcraft** [comment]
well yeah that's what I thought, but like I said, when I use the Docker host IP and the port that is mapped, it works fine.
Here's my docker-compose:
```
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    hostname: dozzle
    networks:
      - mynet
    ports:
      - "9999:8080/tcp"
    environment:
      TZ: 'Europe/Luxembourg'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped

```
