### ISSUE TITLE
Dozzle container crashes when DOZZLE_FILTER set to ""

### ISSUE THREAD

**Issue by obalunenko** [amir20/dozzle#1169]
**Describe the bug**
Dozzle container crashes when DOZZLE_FILTER set to ""

**To Reproduce**
1. Create docker-compose file:
```
version: '3'
services:
  logs:
    container_name: dozzle_logs
    networks:
      - melmetrics
    image: amir20/dozzle:v3.6.2
    environment:
      DOZZLE_ADDR: :9999
      DOZZLE_BASE: /
      DOZZLE_LEVEL: debug
      DOZZLE_TAILSIZE: 300
      DOZZLE_USERNAME: ""
      DOZZLE_PASSWORD: ""
      DOZZLE_KEY: ""
      DOZZLE_FILTER: ""
      DOZZLE_NO_ANALYTICS: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:9999
    expose:
      - 9999

```
2. Run container `docker-compose up --build`
3. List all containers `docker ps -a`
4. Find container ID of `dozzle _logs`
5. `docker logs [container-id]`

**Expected behavior**
The container should run without failures

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Docker version: 20.10.5
 - Browser: doesn't matter
 - Version: v3.6.2

**If applicable include logs with `--level debug` and browser logs**
v3.6.2

Usage: dozzle [--addr ADDR] [--base BASE] [--level LEVEL] [--tailsize TAILSIZE] [--filter FILTER] [--key KEY] [--username USERNAME] [--password PASSWORD] [--no-analytics]

error: error reading a CSV string from environment variable DOZZLE_FILTER with multiple values: EOF
