### ISSUE TITLE
No containers are shown

### ISSUE THREAD

**Issue by tabacman86** [amir20/dozzle#1510]
Describe the bug
No containers are shown on the UI

To Reproduce

Installed using Docker-compose:

```
version: "3.7"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    restart: unless-stopped
```

The dozzle container works on port 8080

Can see web interface but no containers

Docker logs:
```
level=info msg="Dozzle version v3.8.0"
level=info msg="Accepting connections on :8080"
level=info msg="Shutting down..."
level=info msg="Dozzle version v3.8.0"
level=info msg="Accepting connections on :8080"
level=info msg="Shutting down..."
level=info msg="Dozzle version v3.8.0"
level=info msg="Accepting connections on :8080"
level=info msg="Dozzle version v3.8.0"
level=info msg="Accepting connections on :8080"
```

Screenshots
![image](https://user-images.githubusercontent.com/38165400/135265568-12dd41f0-f484-41cd-98c4-8678f7de1b33.png)

Env:
```
OS: Linux (CentOS 7)
Docker version 20.10.8, build 3967b7d
Client: 
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: xfs

Browser & version Mac, Chrome 93.0
Dozzle Version: v3.8.0
```

Thanks for the help
Ori.
