### ISSUE TITLE
ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by cikichen** [amir20/dozzle#1803]
**Describe the bug**
<img width="907" alt="image" src="https://user-images.githubusercontent.com/1478821/178184750-076a88c3-8657-4629-b960-7022d4f3989f.png">

<img width="768" alt="image" src="https://user-images.githubusercontent.com/1478821/178184831-79747e6e-d26f-416c-a300-385f2e1f70eb.png">

<img width="521" alt="image" src="https://user-images.githubusercontent.com/1478821/178184965-92618dc3-ef5f-4781-9140-7e1a3b12e618.png">

```
version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
```

**Desktop (please complete the following information):**
 - OS: centos
 - Docker version 1.13.1
- docker-compose version 1.18.0, build 8dd22a9
- Docker Root Dir: /data/docker
