### ISSUE TITLE
Docker Engine: Cannot connect to the Docker daemon at unix:///var/run/docker.sock  (Where do i find docker.sock ?)

### ISSUE THREAD

**Issue by nodecentral** [amir20/dozzle#1987]
**Describe the bug**
Sorry not exactly sure where to ask this, but I’m trying to set up Dozzle for the first time using the following Docker Compose which is not working .
````
version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /share/Container/dozzle/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
````
Being relatively new to Docker Containers It’s likely something straight forward but I couldnt’ seem to find an answer, so hoping someone can help.

**To Reproduce**
I used the earlier  Docker Compose, mapped to a local volume and it returned the following in the logs.
````

[/] # docker logs -f dozzle
level=info msg="Dozzle version v4.6.0"
level=fatal msg="Could not connect to Docker Engine: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
````
**Expected behavior**
I was hoping it would populate the docker.sock (file?) for me 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [QNAP Linux]
 - Docker version [Docker version 20.10.17-qnap5, build 0474f29]
 - Browser & version [Safari iOS latest]
 - Version [4.6.0]
