### ISSUE TITLE
docker.sock is required even with DOZZLE_REMOTE_HOST configured

### ISSUE THREAD

**Issue by rpatel3001** [amir20/dozzle#2105]
**Describe the bug**
Container does not start when a local docker socket is not provided. This makes using a socket proxy useless.

**To Reproduce**
Start Dozzle with DOZZLE_REMOTE_HOST configured and no docker.sock volume mounted.

**Expected behavior**
Normal startup

**Desktop (please complete the following information):**

- OS: Linux
- Docker version 23.0.2
- Version 4.9.1

level=fatal msg="Could not connect to Docker Engine: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

**Comment by amir20** [comment]
That's right. It's not a bug. More like a feature request. When I added remote hosts, there was existing logic that assumed there is always a docker client. So I haven't refactored the code to not require a client. Currently, this is the easiest way. I'll probably get to it later, but for now, I am still fixing other bugs.

**Comment by jakejarvis** [comment]
@rpatel3001 Just a thought, is it possible that Dozzle is starting before your socket proxy is ready?

I have docker-socket-proxy and Dozzle in the same compose file (short example below) and this works fine without mounting `docker.sock` to Dozzle directly — but note the `depends_on` check that makes Dozzle wait until `docker-proxy` has started, which might be the key to fixing your problem...

```yaml
services:
  docker-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:nightly
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      IMAGES: 1
      INFO: 1
      SERVICES: 1

  dozzle:
    image: amir20/dozzle:master
    depends_on:
      docker-proxy:
        condition: service_started
    environment:
      DOCKER_HOST: tcp://docker-proxy:2375
```
