### ISSUE TITLE
Nothing load, or when it does, nothing to show :/

### ISSUE THREAD

**Issue by judzk** [amir20/dozzle#2205]
Hi, I read the FAQ, but it doesn't apply on my case cause i use no reverse proxy.
Docker on debian 11
Traefik for reverse proxy, but i don't use it for dozzle
When i check the console in dev mode :
```
checked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING
Failed to load resource: the server responded with a status of 404 (Not Found)
EventSource failed: {"isTrusted":true}
```
Any idea?
But the tool seem realy great !

**Comment by amir20** [comment]
It's hard to help on this issue because I don't have enough details. 

1. Could you share how to run Dozzle?
2. Are there any network errors? 


> Failed to load resource: the server responded with a status of 404 (Not Found)

That doesn't seem right. But I don't know which request is throwing that error. 

Sounds like something is misconfigured.

**Comment by judzk** [comment]
Hi, thanks for the reply, i don't see any networks error
Here some log when i use the webui
```
dozzle  | level=debug msg="stopping stats streaming for container ed516a45246e"
dozzle  | level=debug msg="stopping stats streaming for container aee7f997a789"
dozzle  | level=debug msg="stopping stats streaming for container 2265c3c71721"
dozzle  | level=debug msg="stopping stats streaming for container f27258113bac"
dozzle  | level=debug msg="stopping stats streaming for container e3aee3fe07f2"
dozzle  | level=debug msg="stopping stats streaming for container ac11ec400350"
dozzle  | level=debug msg="stopping stats streaming for container fbab3302f903"
dozzle  | level=debug msg="stopping stats streaming for container 07adc5c57142"
dozzle  | level=debug msg="stopping stats streaming for container 93ac9089bcaa"
dozzle  | level=debug msg="stopping stats streaming for container 2e2852031566"
dozzle  | level=debug msg="starting to stream stats for: 2e2852031566"
dozzle  | level=debug msg="starting to stream stats for: 93ac9089bcaa"
dozzle  | level=debug msg="starting to stream stats for: 07adc5c57142"
dozzle  | level=debug msg="starting to stream stats for: fbab3302f903"
dozzle  | level=debug msg="starting to stream stats for: ac11ec400350"
dozzle  | level=debug msg="starting to stream stats for: e3aee3fe07f2"
dozzle  | level=debug msg="starting to stream stats for: aee7f997a789"
dozzle  | level=debug msg="starting to stream stats for: ed516a45246e"
dozzle  | level=debug msg="starting to stream stats for: f27258113bac"
dozzle  | level=debug msg="starting to stream stats for: 2265c3c71721"
dozzle  | level=trace msg="ignoring docker event: exec_create: /dozzle healthcheck"
dozzle  | level=trace msg="ignoring docker event: exec_start: /dozzle healthcheck"
dozzle  | level=trace msg="Executing healthcheck request"
dozzle  | level=trace msg="ignoring docker event: exec_die"
dozzle  | level=trace msg="ignoring docker event: exec_create: /bin/sh -c /app/healthcheck.sh"
dozzle  | level=trace msg="ignoring docker event: exec_start: /bin/sh -c /app/healthcheck.sh"
dozzle  | level=trace msg="ignoring docker event: exec_die"
dozzle  | level=trace msg="ignoring docker event: exec_create: /dozzle healthcheck"
dozzle  | level=trace msg="ignoring docker event: exec_start: /dozzle healthcheck"
dozzle  | level=trace msg="Executing healthcheck request"
dozzle  | level=trace msg="ignoring docker event: exec_die"
```

I just use a docker-compose

```
version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:8080
    environment:
      DOZZLE_LEVEL: trace
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped

```
I'm on debian 11, fresh install from yesterday, juste apt update and docker on it.
