### ISSUE TITLE
Multiple Hosts: Server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by ethanopp** [amir20/dozzle#2226]
**Describe the bug**
I am trying to get dozzle on my remote host setup but running into an HTTPS error:
`error while encoding containers to stream: error during connect: Get \"https://192.168.50.3:1234/v1.24/containers/json?all=1\": http: server gave HTTP response to HTTPS client`

**To Reproduce**
Host:
```  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_REMOTE_HOST=tcp://192.168.50.3:1234
    ports:
      - 1234:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /share/CACHEDEV2_DATA/.qpkg/container-station/etc/docker/tls:/certs
    networks:
      container_network:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
```
Remote (192.168.50.3)
```
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    ports:
      - 1234:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /share/CACHEDEV1_DATA/.qpkg/container-station/etc/docker/tls:/certs
    networks:
      container_network:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped

```
