### ISSUE TITLE
ports are removed from host address 

### ISSUE THREAD

**Issue by azhezzzz** [amir20/dozzle#2279]
**Describe the bug**
- when i use the `DOZZLE_REMOTE_HOST=tcp://167.99.1.1:2376|foo.com` to deploy, its fail

**To Reproduce**
docker compose up with the file
```
version: "3.8"

services:
  dozzle:
    container_name: dozzle-test
    image: amir20/dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8787:8080
    environment:
      - DOZZLE_REMOTE_HOST=tcp://167.99.1.1:2376|foo.com
```

**Expected behavior**
it should show 
`Could not connect to remote host tcp://167.99.1.1:2376`

**Screenshots**

![image](https://github.com/amir20/dozzle/assets/52311721/c98d7f33-ec7a-40c1-a2e3-f942b70d0168)

**Desktop (please complete the following information):**

- OS:  Mac Os
- Docker version: 24.0.2
- Browser & version: chrome
- Version: v4.10.17

**If applicable include logs with `--level debug` and browser logs**
`level=warning msg="Could not create client for tcp://167.99.1.1:2376|foo.com: parse \"tcp://167.99.1.1:2376|foo.com\": invalid port \":2376|foo.com\" after host"
`
