### ISSUE TITLE
dozzle wont connect to docker when socket-proxy is configuered

### ISSUE THREAD

**Issue by Forsskieken** [amir20/dozzle#2385]
**Describe the bug**
In Proxmox on LXC 103 with Traefik2 dozzle runs in a docker environment 
In LXC 110 without Traefik dozzleapps doesn't connect to docker due to socket-proxy

**To Reproduce**
In LXC 110 enable/disable the following lines.
```
      socket-apps-proxy:
        ipv4_address: 192.168.101.77
      DOCKER_HOST: tcp://socket-proxy:2375 
      #- /var/run/docker.sock:/var/run/docker.sock 

```
**Expected behavior**
I expected the same behaviour as in LXC 103.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Ubuntu 22.04.2 LTS in a Proxmox LXC]
- Docker version [  Version:          23.0.1  API version:  1.42]
- Browser & version [firefox 117.0.1]
- Version [4.11.4]

**If applicable include logs with `--level debug` and browser logs**
root@APPS:/home/guyf/docker# docker logs -tf --tail="50" dozzleapps
2023-09-21T08:57:35.476914365Z INFO Dozzle version v4.11.4                       
2023-09-21T08:57:35.476949495Z DEBUG filterArgs = {map[status:map[running:true]]} 
2023-09-21T08:58:11.504594358Z DEBUG Local Docker Engine not found                
2023-09-21T08:58:11.504624954Z FATAL Could not connect to any Docker Engines      

These are my networks in docker-compose.yml
```
version: "3.9"


networks:
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
       - subnet: 192.168.90.0/24

  default:
    driver: bridge

  socket-apps-proxy:
    name: socket-apps-proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
```
        
        
  This is the entry from dozzle in the same docker-compose.yml
```
  dozzleapps:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: amir20/dozzle:latest
    container_name: dozzleapps
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.77 # You can specify a static IP
      socket-apps-proxy:
        ipv4_address: 192.168.101.77
    ports:
      - "8081:8080" # qBittorrent is using port 8080. 
    #command: tcp://socket-proxy:2375
    environment:
      DOZZLE_FILTER: "status=running"
      # DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label.
      DOCKER_HOST: tcp://socket-proxy:2375 # Use this instead if you have Socket Proxy enabled.
      DOZZLE_LEVEL: debug
    #volumes:
      #- /var/run/docker.sock:/var/run/docker.sock # Use Docker Socket Proxy and comment this line for improved security.      environment:

    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.dozzleapps-rtr.entrypoints=https"
      - "traefik.http.routers.dozzleapps-rtr.rule=Host(`dozzleapps.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.dozzleapps-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.dozzleapps-rtr.service=dozzleapps-svc"
      - "traefik.http.services.dozzleapps-svc.loadbalancer.server.port=8080"
```
      
   In my other LXC 103 I use almost the same config only dozzleapps is called dozzle
