### ISSUE TITLE
Dozzle for swarm

### ISSUE THREAD

**Issue by prokrypt** [amir20/dozzle#2495]
```
version: "3.2"
services:
  proxy:
    image: tecnativa/docker-socket-proxy:nightly
    ports:
      - target: 2375
        published: 2375
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
  app:
    environment:
      - DOZZLE_HOSTNAME=pi4
      - DOZZLE_REMOTE_HOST=tcp://10.1.1.1:2375|pi4-1,tcp://10.1.1.2:2375|pi4-2,tcp://10.1.1.3:2375|pi4-3,tcp://10.1.1.4:2375|pi4-4
    image: amir20/dozzle:latest
    deploy:
      mode: global
      placement:
        constraints: 
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9999:8080
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 30s
      timeout: 5s
      retries: 1
```
I thought it couldn't be done, but everything seems to work correctly. Am I doin' it right?
![dozzles](https://github.com/amir20/dozzle/assets/1832555/e1099ef8-5501-48f4-b701-459783faeeab)
