### ISSUE TITLE
Dozzle container does not start with only "remote" engines configured

### ISSUE THREAD

**Issue by aroberts** [amir20/dozzle#2506]
**Describe the bug**
It appears that Dozzle assumes it will always have a "primary" docker engine to connect to, as well as any additional engines via DOZZLE_REMOTE_HOST. Without DOCKER_HOST configured or the docker socket shared as a volume, the container will not start. I am provisioning dozzle via a script, so I have to peel off the first host and use it as `DOCKER_HOST` (separately configuring `DOZZLE_HOSTNAME`, since the pipe syntax introduced in `DOZZLE_REMOTE_HOST` is not understood by `DOCKER_HOST`). The error you get without a "primary" docker connection configured is also unclear.

For compatibility reasons, you probably don't want to just kill off the old approach, so I would suggest just pooling all the collected docker configurations (DOCKER_HOST, volume, remote hosts) and then requiring cardinality >1 of connectable configurations.

**To Reproduce**
Set up docker socket proxies on `example01` and `example02`
```
services:
   dozzle:
    image: amir20/dozzle:latest
    environment:
      - "DOZZLE_REMOTE_HOST=tcp://example01:2375|host1,tcp://example02:2375|host2"
```

**Expected behavior**
container starts

**Desktop (please complete the following information):**
Dozzle v5.4.2
Docker 24.0.7
