### ISSUE TITLE
File Based User Management is not working

### ISSUE THREAD

**Issue by mariushosting** [amir20/dozzle#2518]
uploaded the users.yml file as per the example provided in the documentation. Created the dozzle folder, mounted the /data
everytime I'm trying to connect I always receive 

level=error msg="Error while creating token: invalid credentials"

I'm trying just to copy paste the example in the documentation. Just nothing works.

**Comment by mariushosting** [comment]
`version: "3.9"
services:
  dozzle:
    container_name: Dozzle
    image: amir20/dozzle:latest
    mem_limit: 3g
    cpu_shares: 768
    restart: on-failure:5
    ports:
      - 8892:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/dozzle/data:/data:rw
    environment:
     DOZZLE_AUTH_PROVIDER: simple`

**Comment by amir20** [comment]
Did you create the password using sha256?

**Comment by mariushosting** [comment]
> I just tested it. It works.
> 
> ```
> version: "3"
> services:
>   dozzle:
>     image: amir20/dozzle:latest
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock
>       - ./data:/data
>     ports:
>       - 8080:8080
>     environment:
>       DOZZLE_AUTH_PROVIDER: simple
> ```
> 
> ```
> users:
>   # "admin" here is username
>   admin:
>     name: "Admin"
>     # Just sha-256 which can be computed with "echo -n password | shasum -a 256"
>     password: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
>     email: me@email.net
> ```
> 
> User name is `admin` and password is `password`.

I have just changed user as per the example below in the users.yml file.

```
  # "admin" here is username
  admin:
    name: "Admin"
    # Just sha-256 which can be computed with "echo -n password | shasum -a 256"
    mariushosting: "d9f14a9b3c0e977e7d32ae9b514308fa44cc5963e0f34638b2303a51cc767dd8"
    email: me@email.net
```
So user is admin and password is mariushosting with the correct sha256 and I cant log in. What is wrong?
