### ISSUE TITLE
HELP: How to connect remote host?

### ISSUE THREAD

**Issue by BrunoAFK** [amir20/dozzle#2536]
OK, I'm stupid and need help if someone can help me. I'm trying to connect to a remote host. I was using this guide for TCL https://docs.docker.com/engine/security/protect-access/

remote docker daemon:

```
{
  "hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"],
  "tls": true,
  "tlscert": "/etc/docker/certs/server-cert.pem",
  "tlskey": "/etc/docker/certs/server-key.pem",
  "tlsverify": true,
  "tlscacert": "/etc/docker/certs/ca.pem"
}
```

dozzle:

```
version: "3"
services:
    dozzle:
      container_name: dozzle
      image: amir20/dozzle:latest
      restart: always
      environment:
        DOZZLE_LEVEL: debug
        DOZZLE_USERNAME_FILE: /run/secrets/dozzle_user
        DOZZLE_PASSWORD_FILE: /run/secrets/dozzle_password
        DOZZLE_HOSTNAME: docker-services
        DOZZLE_REMOTE_HOST: tcp://10.0.60.46:2375
      volumes:
        - ./certs:/certs
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 9999:8080
      secrets:
        - dozzle_user
        - dozzle_password
secrets:
    dozzle_user:
      file: dozzle_user.txt
    dozzle_password:
      file: dozzle_password.txt
```

all certificates are in certs folder, and im getting this error:

`level=warning msg="Could not connect to remote host tcp:10.0.60.46:2375: error during connect: Get \"https://10.0.60.46:2375/v1.24/containers/json?all=1\": tls: failed to verify certificate: x509: cannot validate certificate for 10.0.60.46 because it doesn't contain any IP SANs"`
