### ISSUE TITLE
User icon shows the "unavailable image link" icon

### ISSUE THREAD

**Issue by truppelito** [amir20/dozzle#2591]
**Describe the bug**
The following is shown:
<img width="136" alt="Screenshot 2023-12-13 at 09 19 24" src="https://github.com/amir20/dozzle/assets/1059798/47afe5c6-7331-41d3-9a23-008ce7a406ee">
I suppose this is not intended behaviour.

**To Reproduce**
I have the following docker compose config:
```
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle/data:/data
    ports:
      - 52043:8080
```

And the following in dozzle/data/users.yml
```
users:
  # "admin" here is username
  admin:
    name: "Admin"
    # Just sha-256 which can be computed with "echo -n password | shasum -a 256"
    password: "..."
```

I have tested with adding an email to the "admin:", but also got the same icon.

**Desktop (please complete the following information):**

- OS: RaspberryPi OS
- Docker version:
```
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:15 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:15 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Browser & version: Chrome, latest
- Version: Dozzle 5.7.0

**Comment by amir20** [comment]
I wasn't able to reproduce this.  I see

<img width="189" alt="Screenshot 2023-12-13 at 8 13 41 AM" src="https://github.com/amir20/dozzle/assets/260667/9b9c60fa-739c-4f6d-8c36-790867fd275b">


I use https://ui-avatars.com/ to generate fallback profile icons when gravatar profile icons don't exist.  So possibly few things could be the problem: 

1. Gravatar or ui-avatars were offline and it broke
2. Images for some reason were blocked 
3. Browser is blocking it, I also use Chrome so doubt it's this one 

If the problem hasn't gone away then right click on the icon and tell me the src of the `<img/>`. That way we can figure out if it is related to something Dozzle is doing.

**Comment by truppelito** [comment]
This is what I see:
<img width="1036" alt="Screenshot 2023-12-14 at 13 33 20" src="https://github.com/amir20/dozzle/assets/1059798/1aa38955-30e6-43dd-bf0c-0c3c46d70872">
It seems the `img` tag just doesn't have a `src` attribute?

**Comment by truppelito** [comment]
I can confirm that, even if I add an email and restart Dozzle, the same still happens. `users.yml`:
```
users:
  # "admin" here is username
  admin:
    name: "Admin"
    # Just sha-256 which can be computed with "echo -n password | shasum -a 256"
    password: "..."
    email: test@test.local

```
