### ISSUE TITLE
Unable to find remote user

### ISSUE THREAD

**Issue by illispi** [amir20/dozzle#2598]
I am using caddy and dozzle, but I am unable to get in and I get this error in docker logs:

> msg="Unable to find remote user. Please check your proxy configuration. Expecting headers Remote-Email, Remote-User, Remote-Name."

This is my ansible task:

```
---
- name: Create dozzle container
  community.docker.docker_container:
    name: dozzle
    image: amir20/dozzle:latest
    pull: true
    state: started
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    security_opts:
      - no-new-privileges:true
    networks:
      - name: caddy
    env:
      DOZZLE_AUTH_PROVIDER: forward-proxy

    labels:
      caddy: "dozzle.{{ domain }}"
      caddy.reverse_proxy: "{{'{{upstreams 8080}}'}}"
      caddy.forward_auth: "authelia:9091"
      caddy.forward_auth.0_uri: "/api/verify?rd=https://auth.{{ domain }}/"
      caddy.forward_auth.1_copy_headers: "Remote-User Remote-Groups Remote-Name Remote-Email"
```

There was similiar issue, but it was fixed so I am not sure what I am doing wrong here.
