### ISSUE TITLE
Forward Proxy Auth + Healthcheck  = Unable to find remote user

### ISSUE THREAD

**Issue by IvanLi-CN** [amir20/dozzle#2643]
**Describe the bug**
After configuring forwardAuth with authelia + traefik according to the Dozzle documentation, enable Healthcheck.

**To Reproduce**

Docker Compose:
```yaml
  # ...

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    expose:
      - 8080
    networks:
      - traefik
    environment:
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_AUTH_PROVIDER: forward-proxy
      DOZZLE_LEVEL: debug
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - reverse-proxy=traefik
      - traefik.http.routers.dozzle.rule=Host(`dozzle.example.com`)
      - traefik.http.routers.dozzle.tls=true
      - traefik.http.routers.dozzle.tls.certresolver=le
      - traefik.http.routers.dozzle.middlewares=authelia@docker
  # ...
```

logs: 
```
dozzle  | level=info msg="Dozzle version v5.8.1"
dozzle  | level=debug msg="filterArgs = {map[]}"
dozzle  | level=debug msg="Connected to local Docker Engine"
dozzle  | level=info msg="Connected to 1 Docker Engine(s)"
dozzle  | level=info msg="Accepting connections on :8080"
dozzle  | level=error msg="Unable to find remote user. Please check your proxy configuration. Expecting headers Remote-Email, Remote-User, Remote-Name."
dozzle  | level=debug msg="Dumping all headers for url //healthcheck"
dozzle  | level=debug msg="User-Agent: [Go-http-client/1.1]"
dozzle  | level=debug msg="Accept-Encoding: [gzip]"
dozzle  | level=error msg="Unable to find remote user. Please check your proxy configuration. Expecting headers Remote-Email, Remote-User, Remote-Name."
dozzle  | level=debug msg="Dumping all headers for url //healthcheck"
dozzle  | level=debug msg="User-Agent: [Go-http-client/1.1]"
dozzle  | level=debug msg="Accept-Encoding: [gzip]"
dozzle  | level=error msg="Unable to find remote user. Please check your proxy configuration. Expecting headers Remote-Email, Remote-User, Remote-Name."
```

If the health check is not enabled and only ForwardProxy is enabled, Dozzle can obtain my user information.

**Desktop (please complete the following information):**

- Docker version 24.0.7
- Version 5.8.1
