### ISSUE TITLE
Authentication error 

### ISSUE THREAD

**Issue by acidburnmonkey** [amir20/dozzle#2666]
Can't log in after the latest update this is the docker compose am using :

``` 
version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dockers/dozzle/data:/data/
    ports:
      - 8281:8080
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_LEVEL: debug
```
this is the users.yml : 

```
users:
  # "admin" here is username
  admin:
    name: "Admin"
    # Just sha-256 which can be computed with "echo -n password | shasum -a 256"
    password: "1234"
```
I have also tried the default admin /password and it doesn't work

**Comment by amir20** [comment]
Did you actually hash the password?

**Comment by acidburnmonkey** [comment]
docker logs dozzle
time="2024-01-07T20:26:27Z" level=info msg="Dozzle version v6.0.3"
time="2024-01-07T20:26:27Z" level=debug msg="filterArgs = {map[]}"
time="2024-01-07T20:26:27Z" level=debug msg="Connected to local Docker Engine"
time="2024-01-07T20:26:27Z" level=info msg="Connected to 1 Docker Engine(s)"
time="2024-01-07T20:26:27Z" level=info msg="Accepting connections on :8080"
time="2024-01-07T20:26:40Z" level=debug msg="Redirecting to login page for url /"
time="2024-01-07T20:26:47Z" level=error msg="Error while creating token: invalid credentials"
time="2024-01-07T20:26:49Z" level=error msg="Error while creating token: invalid credentials"
time="2024-01-07T20:26:50Z" level=error msg="Error while creating token: invalid credentials"

**Comment by amir20** [comment]
Logs look fine. You password is probably not hashed correctly. It works for other people so I am not sure what different. Make sure it is hashed value.

**Comment by acidburnmonkey** [comment]
yeah it was a hashing issue thanks

**Comment by romquenin** [comment]
I'm having the same kind of issue on Synology:

```
 ERR Failed to create token | error=invalid credentials
```

```
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/dozzle/data:/data
    ports:
      - 9999:8080
    environment:
    - TZ=Europe/Paris 
    - DOZZLE_AUTH_PROVIDER=simple   
    restart: unless-stopped
    networks:
      - default
```

I have generated the password with the following command from the guide:

```
roman@Diskstation:/volume1/docker/dozzle$ docker run amir20/dozzle generate --name Admin --email romquenin@gmail.com --password secret admin
users:
    admin:
        email: romquenin@gmail.com
        name: Admin
        password: $2a$11$IH3rvp8pNKrguonYSZoaV.ueI.00A1umQANXqlM91m0NZeDieJb/i
```

I really don't understand what's wrong here.

Thanks in advance.
