### ISSUE TITLE
CPU and RAM always 0%

### ISSUE THREAD

**Issue by marcinwolosz** [amir20/dozzle#2673]
I use dozzle to display logs via the API. Unfortunately I keep seeing that the CPU and RAM usage is 0%. Where to look for the problem? It's very simple configuration. 

Compose:

```
version: "3"
services:
  dozzle:
    image: amir20/dozzle:latest
    ports:
      - 8080:8080
    environment:
      DOZZLE_REMOTE_HOST: tcp://192.168.11.215:2376|OnDemand
      DOZZLE_BASE: /logs
      DOZZLE_LEVEL: debug
      DOZZLE_ENABLE_ACTIONS: 0
```

![Zrzut ekranu 2024-01-09 151421](https://github.com/amir20/dozzle/assets/26607977/4160fc63-e120-4f57-94e7-43c45ac5915f)

```
Client: Mirantis Container Runtime
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.12m2
 Git commit:        591094d
 Built:             12/21/2021 21:34:30
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Mirantis Container Runtime
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.16.12m2
  Git commit:       9b96ce992b
  Built:            12/21/2021 21:33:06
  OS/Arch:          windows/amd64
  Experimental:     false
```

i see logs like this:
```
time="2024-01-09T14:19:44Z" level=debug msg="starting to stream stats for: b19406cf1561"
time="2024-01-09T14:19:44Z" level=debug msg="starting to stream stats for: bd0e9fb7cbd2"
time="2024-01-09T14:19:44Z" level=debug msg="starting to stream stats for: bd0e9fb7cbd2"
time="2024-01-09T14:19:44Z" level=debug msg="starting to stream stats for: d4939fb51d76"
time="2024-01-09T14:19:44Z" level=debug msg="starting to stream stats for: c1481a25efdf"
time="2024-01-09T14:19:44Z" level=debug msg="starting to stream stats for: d4939fb51d76"
time="2024-01-09T14:19:44Z" level=debug msg="starting to stream stats for: 6d1e5384445e"
time="2024-01-09T14:19:44Z" level=debug msg="starting to stream stats for: 87e391afadfa"
time="2024-01-09T14:19:44Z" level=debug msg="starting to stream stats for: c1481a25efdf"
```

At the same time, I'm able to read all stats using portainer which is also connected via the API
