### ISSUE TITLE
Optimize docker compose

### ISSUE THREAD

**Issue by Feriman22** [amir20/dozzle#2697]
Hi,

In the current docker compose file, the docker.sock file is given full access (read/write), which is a security risk. I'd suggest to use :ro parameter, the app works well with reduced permissions. Here is the corrected version:

```
version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080
```

Feriman
