### ISSUE TITLE
Remote host causes crashes

### ISSUE THREAD

**Issue by grosejon** [amir20/dozzle#2828]
After starting up with localhost and one remote host, I receive this error in the log:

```
time="2024-03-15T01:18:23Z" level=info msg="Dozzle version v6.3.1"
time="2024-03-15T01:18:23Z" level=info msg="Creating client for [redacted] with tcp://[remote host ip]:2375"
time="2024-03-15T01:18:23Z" level=info msg="Connected to 2 Docker Engine(s)"
time="2024-03-15T01:18:23Z" level=info msg="Accepting connections on :8080"
time="2024-03-15T01:28:23Z" level=fatal msg="error while listening to docker events: unexpected EOF. Exiting..."
```

Both hosts are using socket proxy. Compose looks like this:
```
version: "3"
networks:
  socket_proxy:
    external: true
  proxy:
    external: true

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    privileged: true
    networks:
      - proxy
      - socket_proxy
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
      - DOZZLE_AUTH_PROVIDER=forward-proxy
      - DOZZLE_REMOTE_HOST=tcp://[remote host ip]:2375|[redacted]
      - DOZZLE_HOSTNAME=[localhost hostname]
    ports:
      - 9167:8080
```

I'm sure I've done something wrong here. Do you see where I've gone wrong?
