### ISSUE TITLE
Reconnect and  Display REMOTE_HOST always

### ISSUE THREAD

**Issue by azhezzzz** [amir20/dozzle#2865]
**Is your feature request related to a problem? Please describe.**
At first I used REMOTE_HOST and it worked fine, 
but when the REMOTE_HOST loses the connection, it will disappear from the left host list, 
and when it regains the connection, it will not display again in the left host list. 
i need to restart the dozzle container to resolve it everytime

**Describe the solution you'd like**
I hope the REMOTE_HOST list can display in the left host list always that i can know which REMOTE_HOST i have.
And the host item have the icon to show if connected.
And the host item can auto reconnect when i open the web page or i can reconnect it by a manual way if the host is disconnect .
At last I really like this project and it helped me a lot,  thank you very much for the project

**Describe alternatives you've considered**

**Additional context**
<img width="384" alt="image" src="https://github.com/amir20/dozzle/assets/52311721/5fcc8fc0-be3f-4b2f-88ad-10768222259d">

**Comment by amir20** [comment]
This sounds like a bug that should be fixed. And I agree it can be improved. I don't use `REMOTE_HOST` a lot personally which is why I never noticed it. 

I am wondering if Dozzle should auto reconnect automatically or try only when the UI is refreshed. I think both are great options with different tradeoffs. 

While reading the code, I did notice that if the events API throws an exception then I log 

```
log.Fatalf("error while listening to docker events: %v. Exiting...", err)
```

So question, when remote connection exits, do you see this error? The part I don't understand is that this is a fatal log which should cause Dozzle to restart. That was my original goal to not reconnect and instead just exit the program so it would reconnect. 

It sounds like you are not getting that error which might mean something else is happening. 

If you don't see that error, do you know what is causing the host to disconnect?

**Comment by amir20** [comment]
I just tested it locally and I do see `error while listening to docker events: unexpected EOF. Exiting...` so let me know what error, if any, you see...

**Comment by amir20** [comment]
Are you using `--restart unless-stopped`?

**Comment by azhezzzz** [comment]
![image](https://github.com/amir20/dozzle/assets/52311721/c5a537e2-d4c1-462b-8c78-48575407c694)

i can see these but not found `Exiting...`

here is my config

```
version: "3"
services:
  dozzle_test:
    container_name: dozzle_test
    restart: always
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 9999:8080
    environment:
      - DOZZLE_REMOTE_HOST=tcp://host.docker.internal:2377|TEST_HOST

  dockerproxy:
    container_name: dockerproxy
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2377:2375
    environment:
      - CONTAINERS=1
```
