### ISSUE TITLE
v 6.4.3 breaks container actions

### ISSUE THREAD

**Issue by taw123** [amir20/dozzle#2883]
**Describe the bug**
Updated to 6.4.3 per usual, and now unable two effect container actions (stop/restart), regressed to v6.4.2 actions work again. 

Issue is independent of Browser. Tested Current Safari & Chrome.

**To Reproduce**
Install, attempt container action, Dozzel UI reports Action Failed/Errror Unexpected.

**Expected behavior**
Container management continues as update updates in the past

**Desktop (please complete the following information):**

- OS: MacOS 10.15.7 (19H2026)
- Docker version: 20.10.27-qnap1
- Browser & version:  Safari 15.6.1 (15613.3.9.1.16, 15613) & Chrome:  15.6.1 (15613.3.9.1.16, 15613) 
- Version [e.g. 1.26.1. Can be found at `<Dozzle-host>/version`]

**Full Docker version**

```
Client:
 Version:           20.10.27-qnap1
 API version:       1.41
 Go version:        go1.19.12
 Git commit:        662936b
 Built:             Mon Dec 25 08:41:44 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.27-qnap1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       8a4e2cd
  Built:            Mon Dec 25 08:42:51 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

Extracted Compose:
```
  Dozzle:
    container_name: Dozzle
    image: amir20/dozzle:v6.4.2
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro     
      - /share/DockerAppData/Dozzle/config:/data
    networks:
      monitor:
    ports:
      - 9998:9998
    hostname: Dozzle.local
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_ADDR: ":9998"
      DOZZLE_NO_ANALYTICS: true
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_ENABLE_ACTIONS: true      

```
