### ISSUE TITLE
invalid filter status=running

### ISSUE THREAD

**Issue by dmd** [amir20/dozzle#291]
https://github.com/amir20/dozzle#with-docker-compose writes:

```
version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_TAILSIZE=100
      - DOZZLE_FILTER='status:running'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
```

But if I try that, I get:

```
dozzle      | time="2020-02-26T19:14:29Z" level=info msg="Parsing 'status:running'"
dozzle      | level=info msg="Dozzle version 1.20.20"
dozzle      | level=fatal msg="Could not connect to Docker Engine: Error response from daemon: Invalid filter ''status:running''"
```
