### ISSUE TITLE
Feature request: Be able to download the logs splitted in multiples files of x mb instead of a single big file

### ISSUE THREAD

**Issue by omasseau** [amir20/dozzle#2923]
Currently when we download the logs of a container it returns one big file.
If the container is configured to keep a lots of logs, lets say 50 files of 20m like in this example :

```
    logging:
      driver: "json-file"
      options:
        max-file: "50"
        max-size: "20m"

```

then the downloaded file could have a size of 1gb.
Opening a file of 1gb in a text editor is problematic. If instead the download would split the logs and return 50 files of 20mb (inside a gzip file), it would allow to easily open each file in a text editor for quick viewing :)

The max file size could be a setting of Dozzle (configurable through the UI or by providing a startup parameter/env variable).
Even better: retrieve the infos of the max-size defined in the container logging configuration (but I don't know if it is possible technically).
