### ISSUE TITLE
JSON logs support

### ISSUE THREAD

**Issue by aristofun** [amir20/dozzle#2940]
Unless it's already in your near plans — I'm happy to make a PR to support rendering of JSON formatted logs. 

Could you please point me to specific files, pieces of code I can start with?

Thanks.

**Comment by amir20** [comment]
What do you mean? JSON formatted logs are already supported. 👀

**Comment by aristofun** [comment]
Sorry my bad, I've got a huge json payload messed up the output UX and made it hard to manage. Which place should I look to tinker with log messages rendering?

**Comment by amir20** [comment]
Ah I see. Share a screenshot.

The file you are looking for is https://github.com/amir20/dozzle/blob/8a2640cd6b08aa18b8d96ada0cfa75a35858d9b7/assets/components/LogViewer/ComplexLogItem.vue#L19-L25

It's pretty simple. Just loop over all the keys in message and show them per line. 

It's all in Vue and instructions to get up and running on README.

**Comment by brando56894** [comment]
Is pretty printing JSON supported? I don't see it mentioned anywhere. Caddy writes logs in JSON by default and you can change it to "console" which is human readable....but it's just as jumbled as compacted JSON is so there's practically zero benefit. Currently I just pipe the log file in jq so I can read it easily.

**Comment by amir20** [comment]
Yes it is. Actually a little more is supported. You can hide / show fields. It is also color coded for easier reading. 

Have you tried Dozzle? I was under the impression that you tried it and it didn't work. But now I am not sure.

**Comment by brando56894** [comment]
Thanks for the lightning quick response haha Yep I have it up and running right now, nothing is color coded for me and the JSON is compacted.  I attempted to set **DOZZLE_FILTER: label=color** like you have in the wiki but it completely removes all the containers from the list and just says "container not found", so I'm assuming I'm doing something wrong?

```
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      TZ: America/New_York
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_FILTER: label=color
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
    ports:
      - 9999:8080
```
