### ISSUE TITLE
Feature Request: Group replicas / tail replicas as a single stream

### ISSUE THREAD

**Issue by madrussa** [amir20/dozzle#2963]
**Is your feature request related to a problem? Please describe.**
We use replicas in our compose stack to simulate running a real world setup. For example we have multiple PHP-FPM instances to catch issues related to run time caching / race conditions in our micro services. This sits behind a simple nginx round robin load balancer. As internal requests are routing between two containers each instance is outputting its logs separately which can make following the order of events difficult.

**Describe the solution you'd like**
It would be useful to combine the tail of replica containers into a single stream. This seems similar to https://github.com/amir20/dozzle/issues/2960 but it be be by replicated container instead. It would still be useful to see the logs of a single container as well, in the event one of the replicas is misbehaving. Alternatively the ability to combine the logs of any specified containers would be useful.

**Describe alternatives you've considered**
I use the side by side view mostly, but this reduces the space available and some of our stack traces are difficult to view in this layout. It's also harder to view the chronological order of the events.

**Additional context**
Excert of our php docker compose:
```
  php:
    build:
      context: ./instances/php
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=8.3
    volumes:
      - ${WORKSPACE_PATH}/:/var/www
    working_dir: /var/www
    deploy:
      mode: replicated
      replicas: 2

  nginx:
    build:
      context: ./instances/nginx
      dockerfile: Dockerfile
    volumes:
      - ./instances/nginx/config:/etc/nginx/conf.d/
      - ${WORKSPACE_PATH}:/var/www
    depends_on:
      - php
```
