### ISSUE TITLE
[HELP] DOZZLE_REMOTE_HOST Usage

### ISSUE THREAD

**Issue by jd-apprentice** [amir20/dozzle#3050]
**Describe the bug**
It is not a bug, i'm just asking for help

My compose file

```
version: "3.8"

services:

  dashdot:
    image: mauricenino/dashdot
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - "/:/mnt/host:ro"
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
    networks:
      lan:
         ipv4_address: 10.5.0.11

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080
    environment:
      DOZZLE_HOSTNAME: node02.local
      DOZZLE_REMOTE_HOST: tcp://192.168.0.251:2375|node01.local

networks:
  lan:
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
```

**Expected behavior**
Be able to have multiples computers inside a single instance of dozzle.

**Screenshots**

![image](https://github.com/amir20/dozzle/assets/68082746/42b7a6b7-442d-41d0-91e6-8459beaf878b)
![image](https://github.com/amir20/dozzle/assets/68082746/af6c664d-677e-44f0-93ed-8d7ce9310e80)

**Additional information**

I have 3 raspberry pi's which I want to monitor since they have mutiple containers running here and there.

Node00 contains a cloudflare tunnel which exposes logs.XXX and is where I'm acceding the dozzle web ui.
Node02 is where I have the container of dozzle running, I'm ok with that machine but can't access to the containers of Node00 and Node01

**Desktop (please complete the following information):**

- OS: Debian 11
- Docker version: 26.1.4
- Version: latest
