### ISSUE TITLE
💁 Feedback request on agent support for swarm and remote hosts 

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#3052]
## Why is agent needed? 

Dozzle doesn't support swarm mode natively. Remote hosts are done by setting up connections with TLS or https://github.com/Tecnativa/docker-socket-proxy. However, there has been many problems with this approach. Here is some I have found: 

1. Security - `docker-socket-proxy` is insecure.  Setting up TLS is the preferred route, but doing so is very complicated. It requires generating certs, updating docker settings and listening to TCP port. 
2. Ease of use - The majority of bugs I get are related to not being able to setup `socket-proxy`. Dozzle works as design but people find the two might break. 
3. Stability - Dozzle uses the native Docker API which handles connectivity. When a connection fails, Dozzle doesn't try to reconnect. A lot of folks have wanted to reconnect. 

Setting up an agent can solve many problems. 

## How will the agent be implemented? 

Currently, I am working on an agent using gRPC. It will use TLS by default. Compose file for swarm might look like: 

```yml

services:
  dozzle:
    image: amir20/dozzle
    ports:
      - "8080:8080"
    environment:
      DOZZLE_MODE: swarm
    deploy:
      mode: global
     endpoint_mode: dnsrr
```

In this `swarm` mode, I want minimum setup. Dozzle will be smart enough to create it's own mesh using `endpoint_mode: dnsrr`. 

For remote hosts, it could look like this: 

```yml
services:
  dozzle:
    image: amir20/dozzle
    ports:
    environment:
      DOZZLE_REMOTE_AGENTS: host1,host2   
```   
 
Where the agents are setup remotely like this: 

```yml
services:
  agent:
    image: amir20/dozzle
    ports:
      - 7007:7007
    environment:
      DOZZLE_MODE: agent
```

In this mode, the agent will expose its own API over port 7007. Then there will be one installation of Dozzle UI which will connect to all agents. 

## Deprecation of remote connections 
I think with the implementation of agents, it would be safe to remove remote connections. However, I am not sure if people still care to use it. I can't imagine a use where remote connection with `socket-proxy` is preferred over Dozzle's own agent. 

## Questions on top of my head
1. How do the sample compose files look? Are they easy enough to use? 
2. How much do folks care about security? 
3. Should the use of `socket-proxy` be removed in the future? 
4. What are some example of wanting to keep remote connections with agent support? 

Feedback welcomed!
