### ISSUE TITLE
Possible Memory Leak With Dozzle In Swarm Mode Deployed Globally

### ISSUE THREAD

**Issue by githubbiswb** [amir20/dozzle#3075]
**Describe the bug**
The memory usage has continued to climb with Dozzle in Swarm Mode, screen shots and my config are below. I am not watching any logs, dozzle is simply running in the background

**To Reproduce**
Deploy Dozzle in Swarm mode with the config and monitor with a tool like Grafana

**Expected behavior**
Memory to level off at some point that is resonable, according to the graph usage before I went to swarm mode was around and under 20MB

**Screenshots**
![Capture](https://github.com/amir20/dozzle/assets/51446227/b807e9a3-f35a-4c3b-8ff1-48d38cb175f6)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Docker version 26.1.4
- Browser & version N/A
- Version 8.0.1

Below is my config
```
version: '3.5'

services:
  dozzle:
    image: dockreg.biswb.com:5000/amir20-dozzle:070524
    environment:
      DOZZLE_MODE: swarm
      DOZZLE_AUTH_PROVIDER: simple
    networks:
      - DockInternalComms      
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
      update_config:
        delay: 20s
        failure_action: rollback     

networks:
  DockInternalComms:
    external: true
```
