### ISSUE TITLE
Globally Deployed Dozzle With Swarm Mode Needs the service to be named dozzle or it doesn't work

### ISSUE THREAD

**Issue by githubbiswb** [amir20/dozzle#3079]
**Describe the bug**
If you name the service in the stack anything other than dozzle you get 
```
level=fatal msg="error looking up swarm services: lookup tasks.dozzle on 127.0.0.11:53: no such host"

```

**To Reproduce**
Make a service with a different name than dozzle, like dozzleme and this issue occurs

**Expected behavior**
It to work regardless of the service name

**Desktop (please complete the following information):**

- OS: Ubuntu
- Docker version 26.1.4
- Browser & version N/A
- Version 8.0.1

My config for refrence
```
services:
  dozzleme:
    image: dockreg.biswb.com:5000/amir20-dozzle:070824
    environment:
      DOZZLE_MODE: swarm
      DOZZLE_AUTH_PROVIDER: simple
    networks:
      - DockInternalComms      
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
      update_config:
        delay: 20s
        failure_action: rollback     

networks:
  DockInternalComms:
    external: true
```
