### ISSUE TITLE
No CPU and no Memory is shown

### ISSUE THREAD

**Issue by Mephisto090** [amir20/dozzle#3103]
**Describe the bug**
In the overview of all "external" servers, no CPU and no memory is shown. Ubuntuserver is the host on which Dozzle runs

**Screenshots**
![image](https://github.com/user-attachments/assets/a503697a-56bb-4470-b915-b08178b1032b)

**Desktop (please complete the following information):**

- OS: Linux Ubuntu
- Docker version: 27.0.3
- Browser & version: Chrome, Firefox, ...
- Version: 8.0.5

**Dozzle-Docker:**
```
services:
  dozzle:
    container_name: Dozzle
    image: amir20/dozzle:latest   
    environment:
      DOZZLE_REMOTE_HOST: tcp://XXX.XXX.XXX.XX:2375|Nginx-Server,tcp://XXX.XXX.XXX.XX:2375|Webserver,tcp://XXX.XXX.XXX.XX0:2375|Mailserver,tcp://XXX.XXX.XXX.XX:2375|Ubuntuserver 2
      DOZZLE_HOSTNAME: Ubuntuserver
      DOZZLE_ENABLE_ACTIONS: true 
      #DOZZLE_AUTH_PROVIDER: simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /data:/data
    ports:
      - 8000:8080
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
```

**Socket-Proxy:** (Ubuntuserver 2)
```
services:
  socket-proxy:
    container_name: Socket-Proxy
    image: lscr.io/linuxserver/socket-proxy:latest
    logging:
      driver: journald
    restart: unless-stopped
    tmpfs:
      - /run
    privileged: true
    ports:
      - 2375:2375
    environment:
      - ALLOW_START=1 #optional
      - ALLOW_STOP=1 #optional
      - ALLOW_RESTARTS=01 #optional
      - CONTAINERS=1  #optional
      - INFO=1 #optional
      - SYSLOGD=1 #optional
      - SYSTEM=1  #optional   
      - VERSION=1 #optional
      - EVENTS=1 #optional
      - NETWORKS=1 #optional
      - PING=1 #optional
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/log:/dev/log
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "2375"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
```
