### ISSUE TITLE
No connection to Dozzle-Agent on remote host (not the same network)

### ISSUE THREAD

**Issue by Mephisto090** [amir20/dozzle#3104]
**Describe the bug**
I can't access a remote host that is not on the same network with the dozzle agent. The server also gives out "strange" things in contrast to the others

**Desktop (please complete the following information):**

- OS: Linux All Ubuntu
- Docker Version (Dozzle Server): 27.0.3
- Docker Version (Remote Host):  26.1.4
- Docker Version (Host on the same network as Dozzle server): 27.0.3
- Version: 8.0.5
- Agent-Version: 7.0.7

**If applicable include logs with `--level debug` and browser logs**

**Dozzle-Server:**
```
time=2024-07-12T09:16:15Z
level=warning
msg=Could not connect to remote agent XXX.XXX.XXX.XXX:7007: failed to get host info: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp XXX.XXX.XXX.XXX:7007: connect: connection refused\"
```

**Remote-Host:**
```
Dozzle-Agent  | v7.0.7
Dozzle-Agent  | Usage: dozzle [--addr ADDR] [--base BASE] [--hostname HOSTNAME] [--level LEVEL] [--auth-provider AUTH-PROVIDER] [--auth-header-user AUTH-HEADER-USER] [--auth-header-email AUTH-HEADER-EMAIL] [--auth-header-name AUTH-HEADER-NAME] [--wait-for-docker-seconds WAIT-FOR-DOCKER-SECONDS] [--enable-actions] [--filter FILTER] [--remote-host REMOTE-HOST] [--no-analytics] <command> [<args>]
Dozzle-Agent  | error: invalid subcommand: agent
Dozzle-Agent  | v7.0.7
Dozzle-Agent  | Usage: dozzle [--addr ADDR] [--base BASE] [--hostname HOSTNAME] [--level LEVEL] [--auth-provider AUTH-PROVIDER] [--auth-header-user AUTH-HEADER-USER] [--auth-header-email AUTH-HEADER-EMAIL] [--auth-header-name AUTH-HEADER-NAME] [--wait-for-docker-seconds WAIT-FOR-DOCKER-SECONDS] [--enable-actions] [--filter FILTER] [--remote-host REMOTE-HOST] [--no-analytics] <command> [<args>]
Dozzle-Agent  | error: invalid subcommand: agent
Dozzle-Agent  | v7.0.7
Dozzle-Agent  | Usage: dozzle [--addr ADDR] [--base BASE] [--hostname HOSTNAME] [--level LEVEL] [--auth-provider AUTH-PROVIDER] [--auth-header-user AUTH-HEADER-USER] [--auth-header-email AUTH-HEADER-EMAIL] [--auth-header-name AUTH-HEADER-NAME] [--wait-for-docker-seconds WAIT-FOR-DOCKER-SECONDS] [--enable-actions] [--filter FILTER] [--remote-host REMOTE-HOST] [--no-analytics] <command> [<args>]
Dozzle-Agent  | error: invalid subcommand: agent
Dozzle-Agent  | v7.0.7
Dozzle-Agent  | Usage: dozzle [--addr ADDR] [--base BASE] [--hostname HOSTNAME] [--level LEVEL] [--auth-provider AUTH-PROVIDER] [--auth-header-user AUTH-HEADER-USER] [--auth-header-email AUTH-HEADER-EMAIL] [--auth-header-name AUTH-HEADER-NAME] [--wait-for-docker-seconds WAIT-FOR-DOCKER-SECONDS] [--enable-actions] [--filter FILTER] [--remote-host REMOTE-HOST] [--no-analytics] <command> [<args>]
Dozzle-Agent  | error: invalid subcommand: agent
Dozzle-Agent  | v7.0.7
Dozzle-Agent  | Usage: dozzle [--addr ADDR] [--base BASE] [--hostname HOSTNAME] [--level LEVEL] [--auth-provider AUTH-PROVIDER] [--auth-header-user AUTH-HEADER-USER] [--auth-header-email AUTH-HEADER-EMAIL] [--auth-header-name AUTH-HEADER-NAME] [--wait-for-docker-seconds WAIT-FOR-DOCKER-SECONDS] [--enable-actions] [--filter FILTER] [--remote-host REMOTE-HOST] [--no-analytics] <command> [<args>]
Dozzle-Agent  | error: invalid subcommand: agent
```

Host on the same network as Dozzle server:
```
Dozzle-Agent  | time="2024-07-12T08:39:23Z" level=info msg="gRPC server listening on [::]:7007"
```

Docker Compose (Dozzle-Server):
```
services:
  dozzle:
    container_name: Dozzle
    image: amir20/dozzle:latest   
    environment:
      DOZZLE_HOSTNAME: Ubuntuserver
      DOZZLE_ENABLE_ACTIONS: true 
      DOZZLE_REMOTE_AGENT: XXX.XXX.XXX.XX:7007,XXX.XXX.XXX.XX7:7007,XXX.XXX.XXX.XX:7007,XXX.XXX.XXX.XX:7007
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8080
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  default:
    name: Dozzle-Network
    driver: bridge
```

Docker Compose (Remote-Host):
```
services:
  dozzle-agent:
    image: amir20/dozzle:latest 
    container_name: Dozzle-Agent
    command: agent  
    environment:
      DOZZLE_HOSTNAME: Mailserver
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007   
    restart: unless-stopped
    networks:
      socket-network:

networks:
  socket-network:
    name: Dozzle-Agent-Network
```

Docker Compose (Host on the same network as Dozzle server):
```
services:
  dozzle-agent:
    image: amir20/dozzle:latest 
    container_name: Dozzle-Agent
    command: agent  
    environment:
      DOZZLE_HOSTNAME: Ubuntuserver-2
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007   
    restart: unless-stopped
    networks:
      socket-network:
        ipv4_address: 172.20.0.3 


networks:
  socket-network:
    name: Socket-Proxy-Network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
```
