### ISSUE TITLE
System becomes irresponsive, 100% resource utilization if high container count

### ISSUE THREAD

**Issue by mistrello96** [amir20/dozzle#3140]
### Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### Dozzle version

8.0.6 (but tried also previous versions)

### ✅ Command used to run Dozzle

docker compose up -d

using this DC

```
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

### Describe the performance issue you are seeing

As soon as i run the container, the CPU usage peaks at 100% and the RAM starts to fill up. The system becomes irresponsive and the only solution is a force reboot. No anomalies in Dozzle logs

Relevant issue #3085

### How many containers, hosts, agents, etc. are you using?

30 active container, 30000 stopped containers with few lines of log (1/2) per container

### Screenshots, videos, or logs

[log.txt](https://github.com/user-attachments/files/16350537/log.txt)
