### ISSUE TITLE
Authentication doesn't work

### ISSUE THREAD

**Issue by alexander-potemkin** [amir20/dozzle#3141]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

8.0.6

### ✅ Command used to run Dozzle

```yaml
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - ./dozzle_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_LEVEL=debug
    ports:
      - 127.0.0.1:8080:8080
```

```bash
# cat ./dozzle_data/users.yml
users:
    admin:
        password: 649ff93cb24fcb77a764d4e86a233b8dcac1c3e9ae04ded35ecd400dc6a329
```

### 🐛 Describe the bug / provide steps to reproduce it

Installed fresh version of dozzle, tried to enabled authentication, but it doesn't work - the page is still accessible for everyone.

Tried restarting everything, including the whole host.

### 💻 Environment

Client: Docker Engine - Community
 Version:    27.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 13
  Running: 9
  Paused: 0
  Stopped: 4
 Images: 9
 Server Version: 27.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-116-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 856.4MiB
 Name: <reducted>
 ID: b35cd0b2-380d-4b90-819e-f967bd2e72d2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

### 📜 If applicable, attach your Dozzle logs. You many need to enable debug mode. See https://dozzle.dev/guide/debugging.

{"time":"2024-07-23T14:48:43Z","level":"info","msg":"Dozzle version v8.0.6"}
{"time":"2024-07-23T14:48:43Z","level":"info","msg":"Connected to 1 Docker Engine(s)"}
{"time":"2024-07-23T14:48:43Z","level":"info","msg":"Accepting connections on :8080"}
