### ISSUE TITLE
Support dozzle agent in Unraid

### ISSUE THREAD

**Issue by sefininio** [amir20/dozzle#3223]
### Describe the feature you would like to see

Hello @amir20 

When installing the Dozzle container on Unraid, I can add the agent port and `DOZZLE_HOSTNAME` variables, but there is no way (that I can find) to provide the `command: agent` part to make the container operate as an agent.

<img width="1260" alt="image" src="https://github.com/user-attachments/assets/124db50b-48be-444f-8601-0d0510fd516a">

Any ideas?

**Comment by sefininio** [comment]
FYI - as a work around, I created the container as agent inside a dedicated docker-compose within unraid. So it is possible as a work around, albeit not in a very obvious way.

Maybe creating a new Unraid dozzle recipe as an agent?

**Comment by amir20** [comment]
I could easily solve this by creating an env like `DOZZLE_MODE=agent`. 

Does Unraid really not have a way to overwrite the command?

**Comment by sefininio** [comment]
I think the env is far better than the command option anyway, but to the point of Unraid - as far as I can see, there is no way other than creating a compose stack 🤷

**Comment by amir20** [comment]
https://github.com/amir20/dozzle/pull/3226 should fix this. You can try it with `amir20/dozzle:pr-3226`. I'd want to update the documentation before releasing. Let me know if it works out.

**Comment by amir20** [comment]
I wanted to try Unraid and play around with it. It doesn't look to be that simple.

**Comment by sefininio** [comment]
Thanks for the quick response!
That doesn't seem to work, though.

I tried on a different server (Unraid wasn't accessible to me just now), with:

```
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:pr-3226
    restart: always
    environment:
      - tailSize=1000
      - DOZZLE_HOSTNAME=family-z2m
      - DOZZLE_MODE=agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9095:7007
      
 ```
And the dozzle UI marked it as offline.
