### ISSUE TITLE
Incorrect sha256 of certain passwords leading to no password working on the login screen for simple auth

### ISSUE THREAD

**Issue by vytautas362** [amir20/dozzle#3254]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

v8.4.1

### ✅ Command used to run Dozzle

```
  docker-logs:
    image: amir20/dozzle:latest
    container_name: docker-logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-logs/data:/data
    ports:
      - '8080:8080'
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
    restart: unless-stopped
    stdin_open: true
    tty: true
```

```
docker run amir20/dozzle generate random --password "%G5A4&G$qVmv9Y" --email redacted@email.com --name "redacted" > users.yml
```
    
```
    users:
    random:
        email: redacted@email.com
        name: redacted
        password: 995ef37b33ff8953112d090c5c4abeae3a0649c06b817363520c7627d8bd3529
```

### 🐛 Describe the bug / provide steps to reproduce it

Launch Dozzle using the instructions listed above.

I believe the issue lies in the incorrect handling of `%` symbol. See:

```
printf "%G5A4&G$qVmv9Y" | sha256sum
c960567bf5345cb4dbcf5d9ea6deda66788f329ab3b983ac6961280c2b9db7f4  -
```

```
printf "%%G5A4&G$qVmv9Y" | sha256sum
995ef37b33ff8953112d090c5c4abeae3a0649c06b817363520c7627d8bd3529  -
```

Neither `%%G5A4&G$qVmv9Y` nor `%G5A4&G$qVmv9Y` work as login passwords.

### 💻 Environment

```
Client: Docker Engine - Community
 Version:    27.1.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 20
  Running: 8
  Paused: 0
  Stopped: 12
 Images: 13
 Server Version: 27.1.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-32-cloud-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.792GiB
 Name: lte-cloud-server
 ID: 157d1e21-c725-4470-877b-0589806e76ac
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 ```

**Comment by amir20** [comment]
Hey @vytautas362 the problem is actually the `$` sign.  I use fish shell and shows that it is trying to replace $ with a variable. 

<img width="254" alt="Screenshot 2024-09-05 at 8 01 19 AM" src="https://github.com/user-attachments/assets/6c52b133-1970-4dec-9047-9008ad8f08ac">

You want to use single quotes instead. 

```
❯ docker run amir20/dozzle generate random --password '%G5A4&G$qVmv9Y'                                                                                                                                         8:19:10
users:
    random:
        email: ""
        name: ""
        password: a70e3add70cf9996754cf42d81bc659f9d111568475c8a6f6fedd4c74e7ddc1e
```

The percent sign is also broken and you can see this with 

```
❯ printf '%G5A4&G$qVmv9Y'                                                                                                                                                                                      8:21:45
05A4&G$qVmv9Y⏎

❯ echo -n '%G5A4&G$qVmv9Y'                                                                                                                                                                                     8:21:55
%G5A4&G$qVmv9Y⏎
```

You want to use `echo -n '%G5A4&G$qVmv9Y' | shasum -a 256` to validate, which produces `a70e3add70cf9996754cf42d81bc659f9d111568475c8a6f6fedd4c74e7ddc1e`.
