### ISSUE TITLE
Dozzle Server becomes unvailable when agent in different subnet/via vpn is not rechable.

### ISSUE THREAD

**Issue by Eldiabolo21** [amir20/dozzle#3275]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Agents

### 📦 Dozzle version

8.4.3

### ✅ Command used to run Dozzle

Docker Compose files for server and agent causing problems

Server
```yaml
services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    environment:
      - DOZZLE_REMOTE_AGENT=192.168.16.32:7007,192.168.16.31:7007,192.168.8.5:7007
      - DOZZLE_HOSTNAME="docker-logs.XXXXX.com"
      - DOZZLE_NO_ANALYTICS=true
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_AUTH_PROVIDER=simple
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s        
    ports:
      - 6789:8080
    restart: unless-stopped
```

Agents: 
```yaml
services:
  dozzle-agent:
    image: amir20/dozzle:latest
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
    restart: unless-stopped
```

### 🐛 Describe the bug / provide steps to reproduce it

Hi people, 

I have a dozzle Server (subnet 192.168.16.0/24) and few other hosts with agents. One of the hosts only reachable through a wireguard Site-To-Site-VPN (subnet 192.168.8.0/24). 

When agents in the same subnet fail to start, the dozzle server just shows a message, which i guess is the expected behaviour. However, when the VPN connection breaks (Not the issue here) the dozzle-server also becomes completely unresponsive. It doesnt exactly crash, but I also can't open the webinterface anymore. Logs just say 

```
dozzle-1  | {"level":"error","error":"host OORC:NYB6:J7QY:4DAB:A26P:ZHLW:J5UZ:6JJW:ATO6:ZG3U:D4FF:BFXX unavailable: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.8.5:7007: i/o timeout\"","time":"2024-09-15T10:24:16Z","message":"Error listing containers"}
```
Server 100 or eben 1000 times over. 
It does come back after some time (roughly 6 mins), but stil. Also, nothing happens if I just regularly stop the agent on the remote site. However I still believe an application should not stall if it can't reach any of its agent, for whatever reason. 

Is this something we can investigate? 

Cheers and thanks for the amazing software! 

### 💻 Environment

Server: 
```
Client: Docker Engine - Community
 Version:    27.2.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 38
  Running: 36
  Paused: 0
  Stopped: 2
 Images: 32
 Server Version: 27.2.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-119-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 11.68GiB
 Name: docker1-1
 ID: 94e94d74-9b3c-434e-bb36-87386cc38ad3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.16.0.0/12, Size: 24
  ```

Agent:
```
Client: Docker Engine - Community
 Version:    27.2.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 10
  Paused: 0
  Stopped: 1
 Images: 14
 Server Version: 27.2.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-119-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.66GiB
 Name: mampi-server
 ID: OORC:NYB6:J7QY:4DAB:A26P:ZHLW:J5UZ:6JJW:ATO6:ZG3U:D4FF:BFXX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
