### ISSUE TITLE
Main page has visual artifacts after fully loading

### ISSUE THREAD

**Issue by dzonder** [amir20/dozzle#3282]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

8.4.4

### ✅ Command used to run Dozzle

```
  dozzle:
    restart: unless-stopped
    image: amir20/dozzle:latest
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
    environment:
      DOZZLE_HOSTNAME: mezz
      DOZZLE_REMOTE_HOST: host1,host2,host3,host4,host5,host6,host7,host8,host9
      DOZZLE_NO_ANALYTICS: true
    ports:
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

### 🐛 Describe the bug / provide steps to reproduce it

See the attached video:
https://github.com/user-attachments/assets/85295771-770a-4de9-aa94-09f419a04cf1

After fully loading the main page is obstructed by black rectangles (some kind of rendering problem). 

This started happening in version 6.6.0 and happens ever since. Chrome/Edge browser is affected. The page renders just fine on Safari.

### 💻 Environment

Browser: `Chrome 128.0.6613.138`

`docker system info` output with some personal info snipped:

```
Client: Docker Engine - Community
 Version:    27.2.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 37
  Running: 37
  Paused: 0
  Stopped: 0
 Images: 38
 Server Version: 27.2.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.31+rpt-rpi-v8
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.759GiB
 Name: #######
 ID: ########
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: #########
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
