### ISSUE TITLE
Swarm - Dashboard show only one node info

### ISSUE THREAD

**Issue by vampywiz17** [amir20/dozzle#3287]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Swarm Mode

### 📦 Dozzle version

v8.5.1

### ✅ Command used to run Dozzle

```
version: "3.6"
services:
  dozzle:
    container_name: dozzle
    image: hun25-21v:5000/amir20/dozzle:latest
    restart: unless-stopped
    deploy:
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.dozzle.entrypoints=websecure"
          - "traefik.http.routers.dozzle.tls=true"
          - "traefik.http.routers.dozzle.rule=Host(`dozzle-rohu.xy.com`)"
          - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
      mode: global
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: users
        target: /data/users.yml
    environment:
      - DOZZLE_MODE=swarm
      - DOZZLE_AUTH_PROVIDER=simple

networks:
  traefik-public:
    external: true

secrets:
  users:
    external: true
```

### 🐛 Describe the bug / provide steps to reproduce it

Dozzle dashboard one one node info show it (CPU/Memory for exampe)

### 💻 Environment

```
hun25-21v:~ # docker system info
Client:
 Version:    25.0.6-ce
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.11.2
    Path:     /usr/lib/docker/cli-plugins/docker-buildx

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 25.0.6-ce
 Storage Driver: btrfs
  Btrfs:
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: active
  NodeID: edou7744br2h7lshq79tvkvab
  Is Manager: true
  ClusterID: k4cjvzi6zwaz91oohepm4p632
  Managers: 1
  Nodes: 3
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 2
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.51.38.92
  Manager Addresses:
   10.51.38.92:2377
 Runtimes: oci runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3a4de459a68952ffb703bbe7f2290861a75b6b67
 runc version: v1.1.14-0-g2c9f5602f0ba
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.4.0-150600.23.17-default
 Operating System: openSUSE Leap 15.6
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.76GiB
 Name: hun25-21v
 ID: 5M2D:3EQB:BXTJ:EVT4:YDNJ:XQ42:XWO3:3HYY:ET44:YJQD:CSSR:4Y27
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  hun25-21v:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### 📸 If applicable, add screenshots to help explain your bug

![image](https://github.com/user-attachments/assets/342f0a1d-30c9-4df4-8732-f6277576a3cf)
****
