### ISSUE TITLE
download log from agent got 0 bytes

### ISSUE THREAD

**Issue by jenggo** [amir20/dozzle#3308]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Agents

### 📦 Dozzle version

8.5.5

### ✅ Command used to run Dozzle

```yaml
services:

  dozzle:
    container_name: dozzle
    image:          amir20/dozzle
    restart:        always
    network_mode:   host
    command: agent
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_FILTER=label=dozzle
      - DOZZLE_HOSTNAME=gcp-1
```

### 🐛 Describe the bug / provide steps to reproduce it

got 0 bytes when download log from agent

### 💻 Environment

```
Client: Docker Engine - Community
 Version:    27.2.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 16
  Running: 16
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 27.2.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-25-cloud-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.763GiB
 Name: propertek-gcp-1
 ID: 41239bdc-7283-4fdc-bc36-fa7f0b8bcfdf
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### 📜 If applicable, attach your Dozzle logs. You many need to enable debug mode. See https://dozzle.dev/guide/debugging.

![Screenshot_20241004_090355](https://github.com/user-attachments/assets/60351f11-2f24-4584-920f-ba8f5c253eeb)
