### ISSUE TITLE
Even more simpler authentication needed

### ISSUE THREAD

**Issue by marcwittke** [amir20/dozzle#3328]
### Describe the feature you would like to see

I would like to use dozzle in docker compose without the need for a `/data/users.yml` file in a volume 

### Describe how you would like to see this feature implemented

solution could look like this:

```yaml
  logviewer:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_USERNAME: admin
      DOZZLE_PASSWORD: "Pa$$w0rd"
```

### Describe any alternatives you've considered

I considered:
- overriding the entrypoint to achieve this, but since the container image is built from `scratch` there is no shell available that let me call two commands combined with `&&`
- a sort of init container like in k8s that writes the file but docker compose doesn't really have such a feature
