### ISSUE TITLE
Disabling one field will disable all fields not part of current log message

### ISSUE THREAD

**Issue by marvinruder** [amir20/dozzle#3339]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Remote Hosts

### 📦 Dozzle version

v8.6.2

### ✅ Command used to run Dozzle

```yaml
services:
  dozzle:
    container_name: dozzle
    hostname: dozzle
    image: amir20/dozzle
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    environment:
      DOZZLE_HOSTNAME: […]
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_REMOTE_AGENT: […]:7007
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped
```

### 🐛 Describe the bug / provide steps to reproduce it

Given that

- a container shows two structured log messages, of which the first holds the fields `time`, `level`, `msg`, the second holds the fields `time`, `level`, `msg`, `port`,
- Local Storage does not hold a value for the key `DOZZLE_VISIBLEKEYS`

When

- clicking on the first message, and
- disabling the field `time`

Then

- only the fields `level` and `msg` are shown, the field `port` is hidden unexpectedly.

### 💻 Environment

```
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 17
  Running: 17
  Paused: 0
  Stopped: 0
 Images: 17
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.10.10-200.fc40.aarch64
 Operating System: Fedora CoreOS 40.20240920.3.0
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.539GiB
 Name: […]
 ID: […]
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: […]
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### 📸 If applicable, add screenshots to help explain your bug

Input:

```logfmt
time=2024-10-23T17:34:38.936Z level=INFO msg="Will accept requests with correct token only"
time=2024-10-23T17:34:38.936Z level=INFO msg="Starting server" port=8245
```

Output after disabling field `time` only:

<img width="480" alt="image" src="https://github.com/user-attachments/assets/95dc2606-ac56-43ee-903e-49537692b828">
<img width="480" alt="image" src="https://github.com/user-attachments/assets/4424d0eb-6809-4de5-a164-b3a43d35050d">
<img width="673" alt="image" src="https://github.com/user-attachments/assets/ab529c79-5de5-4c80-82c9-61fef64dd4d3">

### 📜 If applicable, attach your Dozzle logs. You many need to enable debug mode. See https://dozzle.dev/guide/debugging.

(omitting this step, not sure this will help here)
