### ISSUE TITLE
Web UI slow with over 200 containers spread across 5 hosts

### ISSUE THREAD

**Issue by adrianipopescu** [amir20/dozzle#3472]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Agents

### 📦 Dozzle version

v8.9.0

### ✅ Command used to run Dozzle

docker compose up -d of 

```
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    user: ${UID}:${GID}
    environment:
      TZ: ${TZ}
      DOZZLE_REMOTE_AGENT: ${DZ_HOSTS}
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.dozzle.rule=Host("logs.${ENV_SD}.${ENV_DOMAIN}")
      - traefik.http.routers.dozzle.entrypoints=https
      - traefik.http.services.dozzle.loadbalancer.server.port=8080

      - homepage.group=Monitors
      - homepage.name=Dozzle
      - homepage.icon=dozzle.svg
      - homepage.href=https://logs.${ENV_SD}.${ENV_DOMAIN}/
      - homepage.description=Docker Aggregateed Logs
    restart: unless-stopped
```
and
```
  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle-agent
    hostname: dozzle-agent
    command: agent
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      #start_interval: 5s
    user: ${UID}:${GID}
    environment:
      TZ: ${TZ}
      DOZZLE_HOSTNAME: ${ENV_SD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
    networks:
      - toolkit
    restart: unless-stopped 
```

### 🐛 Describe the bug / provide steps to reproduce it

It started off similarily to https://github.com/amir20/dozzle/issues/3225 but I think I'm throwing too much at it, all at once.
An example agent on a vm with ±12 cores eats up around 2% of the cpu. 

Here is a profile from a firefox attempt to view logs that crashed the browser on an M1 mac: https://profiler.firefox.com/public/xdh84dzn3w71spbg3c8qgexrrvwtw2yn6c8zz00/calltree/?globalTrackOrder=01&implementation=js&thread=2&v=10

Is there a process to diagnose what's going on?

### 💻 Environment

```
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /root/.docker/cli-plugins/docker-compose

Server:
 Containers: 51
  Running: 49
  Paused: 0
  Stopped: 2
 Images: 63
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 57f17b0a6295a39009d861b89e3b3b87b005ca27
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.12-2-pve
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 16GiB
 Name: experiments
 ID: ee199d4c-da27-44c7-a858-56e5f34b3968
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### 📸 If applicable, add screenshots to help explain your bug

<img width="694" alt="image" src="https://github.com/user-attachments/assets/b5355e76-a85f-4ba3-ba5b-1da4045d54c1" />
