### ISSUE TITLE
Can't properly use traefik with dozzle in Swarm Mode

### ISSUE THREAD

**Issue by realitix** [amir20/dozzle#3489]
### Describe the feature you would like to see

When I configure Dozzle in global mode (swarm mode), I want to add Traefik labels to route through the proxy. However, I don't want Traefik to randomly route to one of the Dozzle nodes; I want it to always route to the same node.

### Describe how you would like to see this feature implemented

Since it's not possible to assign Traefik labels to only one service when the deployment is in global mode, you need to create a "front" service and the other services separately.
For example:

```yaml
services:
  dozzle-front:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=swarm
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.dozzle.rule=Host(`dozzle.example.com`)
        - traefik.http.services.dozzle.loadbalancer.server.port=8080
        - traefik.http.routers.dozzle.entrypoints=websecure
        - traefik.http.routers.dozzle.tls.certresolver=myresolver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
  dozzle-global:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=swarm
    deploy:
      mode: global
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

networks:
  proxy:
    external: true
```

Explanation:
dozzle-front Service:

This service is limited to one replica (replicas: 1).
It has the Traefik labels for routing traffic.
It acts as the entry point for Traefik.
dozzle-global Service:

This is deployed in global mode, running on all nodes.
It does not have Traefik labels, ensuring that Traefik routes traffic only through the dozzle-front service.
This configuration ensures that Traefik always routes to the same node (dozzle-front), while dozzle-global handles the global deployment requirements.

Currently, this configuration will not work because Dozzle relies on the service name in swarm mode, and the services do not have the same name. It should be possible to manually set the service name (in which case, we could use the same name for both services).
