### ISSUE TITLE
Dozzle in swarm not connecting to agent

### ISSUE THREAD

**Issue by michaelmegrath** [amir20/dozzle#3512]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Swarm Mode

### 📦 Dozzle version

8.10.0

### ✅ Command used to run Dozzle

Swarm config:
```
services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=swarm
      - DOZZLE_REMOTE_AGENT=10.0.0.220:7007
      - DOZZLE_LEVEL=debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    networks:
      - swarm-net
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dozzle.entrypoints=websecure"
        - "traefik.http.routers.dozzle.rule=Host(`dozzle.domain.com`) || Host(`dozzle.domain2.com`)"
        - "traefik.http.routers.dozzle.tls=true" 
        - "traefik.http.services.dozzle.loadbalancer.server.port=8080"

networks:
  swarm-net:
    external: true
```
Agent Config:
```
services:
  dozzle-agent:
    image: amir20/dozzle:latest
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
```

### 🐛 Describe the bug / provide steps to reproduce it

Sorry if this is too similar to Issue  #3344.  There was no resolution for that issue and I am running in swarm mode which may be part of the problem potentially.

All my container in my docker swarm are configured and working properly.  I am trying to connect a host not on the docker swarm via the agent.  It says the host is offline. 

I have from a container in the same network/swarm as the dozzle server run this:
```
fa9c77bb6918:/config# nc -zv 10.0.0.220 7007
10.0.0.220 (10.0.0.220:7007) open
```
So it doesn't appear to be a firewall issue, which has me stumped.

### 💻 Environment

Dozzle Server's Environment
```
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 15
  Running: 12
  Paused: 0
  Stopped: 3
 Images: 15
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: active
  NodeID: b81iil83oghyt5cbwzjhvgs7p
  Is Manager: true
  ClusterID: 0op70i0f2m59i8qhd7unl50ng
  Managers: 2
  Nodes: 4
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.0.0.228
  Manager Addresses:
   10.0.0.228:2377
   10.0.0.238:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-1013-raspi
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.752GiB
 Name: host1
 ID: 08822b6f-63ac-4052-95e6-379f56fc5430
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: Running Swarm in a two-manager configuration. This configuration provides
         no fault tolerance, and poses a high risk to lose control over the cluster.
         Refer to https://docs.docker.com/engine/swarm/admin_guide/ to configure the
         Swarm for fault-tolerance.
```
Dozzle agent's Environment
```
sudo docker system info
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 9
  Paused: 0
  Stopped: 2
 Images: 35
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.11.0-1004-raspi
 Operating System: Ubuntu 24.10
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.751GiB
 Name: host2
 ID: cf7d5348-d8e1-4b40-ae2e-bf0b0c6e45c2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### 📸 If applicable, add screenshots to help explain your bug

![Screenshot 2025-01-06 at 4 00 58 PM](https://github.com/user-attachments/assets/be3456f1-be6f-4876-9482-9ca992db1c27)

### 📜 If applicable, attach your Dozzle logs. You many need to enable debug mode. See https://dozzle.dev/guide/debugging.

{
  "level": "warn",
  "error": "rpc error: code = DeadlineExceeded desc = received context error while waiting for new LB policy update: context deadline exceeded",
  "endpoint": "10.0.0.220:7007",
  "time": "2025-01-07T00:01:10Z",
  "message": "error fetching host info for agent"
}
