### ISSUE TITLE
Healtcheck

### ISSUE THREAD

**Issue by Arelius-D** [amir20/dozzle#3513]
### Describe the feature you would like to see

Built in healtcheck

### Describe how you would like to see this feature implemented

```
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
```
