### ISSUE TITLE
Sonarr debug and trace logs not appearing in Dozzle

### ISSUE THREAD

**Issue by Hark0q** [amir20/dozzle#3514]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

v8.9.1

### ✅ Command used to run Dozzle

```
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /htpc/config/dozzle:/data
    ports:
      - 9988:8080
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_LEVEL: debug
```

### 🐛 Describe the bug / provide steps to reproduce it

Sonarr (Version 4.0.12.2823) is configured to log Trace level logging. This creates three sets of logs files: info, debug and trace.

Dozzle only displays the info level logs. 
<img width="1454" alt="image" src="https://github.com/user-attachments/assets/2b6c68f8-af0a-4baa-833d-3938aa48f10d" />

Sonarr run with this compose file:
```
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/sonarr:/config
      - /data/media/ssd4tb/unsorted:/data/unsorted/
      - /data/:/data/
      - /data/unsorted/complete/:/data/media/unsorted/complete
      - ${BACKUP}/sonarr:/backup
    network_mode: service:gluetun
    depends_on:
      gluetun:    
        condition: service_healthy
    labels:
      - dev.dozzle.group=htpc
```

```
$ cat config/sonarr/config.xml | grep -i log
  <LogLevel>trace</LogLevel>
  <SyslogPort>514</SyslogPort>
  <LogSizeLimit>10</LogSizeLimit>
```

### 💻 Environment

```
Client: Docker Engine - Community
 Version:    27.4.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.3
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.32.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 30
  Running: 22
  Paused: 0
  Stopped: 8
 Images: 114
 Server Version: 27.4.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-50-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 30.98GiB
 Name: nuc
 ID: 127bf0d2-e22a-46b7-a5b6-f1e52d495f0b
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: oqcira
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

### 📜 If applicable, attach your Dozzle logs. You many need to enable debug mode. See https://dozzle.dev/guide/debugging.

[container-logs-2025-01-07T05-01-10.zip](https://github.com/user-attachments/files/18327811/container-logs-2025-01-07T05-01-10.zip)
