### ISSUE TITLE
Ability to set  a display name coming from a env var  in the title tag and in the page header  

### ISSUE THREAD

**Issue by UnclePhil** [amir20/dozzle#3515]
### Describe the feature you would like to see

I use Dozzle on 16 swarm clusters, and sometimes I've 4 or 5 instances open in the same browser with all difficulties to find the good one.
It will be fine to have a Env var with a display name appearing in the title tag and in the header of the application.

BTW your app is a killer one. 
best regards

### Describe how you would like to see this feature implemented

- Create a  DOZZLE_TITLE envvar  
- Inject it in the title tag, and in the header of the nav bar, in-place of under the svg logo

**Comment by amir20** [comment]
https://dozzle.dev/guide/hostname

Isn't this already done?

**Comment by UnclePhil** [comment]
Sorry, 
I totally pass over this setting. 
It work perfectly. 
already loaded on all clusters

**Comment by UnclePhil** [comment]
And i rollback, 
because when you put  the --hostname flag on a swarm implementation in global mode, all swarm host in the right display have the same name.   But i need the real host name !!

```
services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=swarm
      - DOZZLE_HOSTNAME=${CLUSTER_NAME}
      - DOZZLE_NO_ANALYTICS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 28080:8080
    networks:
      - dozzle
    deploy:
      mode: global
    ...
```
The display 
![image](https://github.com/user-attachments/assets/9922899a-5f4f-4095-9acd-12987c5b8ce3)
