### ISSUE TITLE
The health check check mark not returning to healthy

### ISSUE THREAD

**Issue by stormbyte** [amir20/dozzle#3590]
### 🔍 Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Remote Hosts

### 📦 Dozzle version

v8.10.5

### ✅ Command used to run Dozzle

```
services:
  dozzle-agent:
    image: amir20/dozzle:latest
    command: agent
    environment:
      - "DOZZLE_HOSTNAME=docker-host-01"
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
```

### 🐛 Describe the bug / provide steps to reproduce it

The conainers with a healthcheck show a transparent block when starting.
When the healthcheck is `healthy` and a green check mark will be shown.
When a container becomes `unhealthy` a red check mark is shown indicating that the container is `unhealthy`.

But when the container becomes healthy again, the check mark doesn't return to green, so containers are shown `unhealthy` but are `healthy`.

### 💻 Environment

```
Client: Docker Engine - Community
 Version:    27.4.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.3
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.32.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 82
  Running: 79
  Paused: 0
  Stopped: 3
 Images: 118
 Server Version: 27.4.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-51-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 13.65GiB
 Name: docker-host-01
 ID: VGNX:GC7O:CNDP:7ESE:VDW6:P3PB:FBTU:RVRZ:YZGZ:W67M:WJH7:JWD4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.16.0.0/12, Size: 20
```
