### ISSUE TITLE
Agent mode and DOCKER_HOST - cannot connect to docker host

### ISSUE THREAD

**Issue by Davo1624** [amir20/dozzle#3660]
### 🔍 Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Agents

### 📦 Dozzle version

8.11.5

### ✅ Command used to run Dozzle

```
  dozzle:
    command:
      - agent
    container_name: dozzle
    environment:
      DOCKER_HOST: tcp://dockerproxy:2375
      DOZZLE_HOSTNAME: racknerd
    image: amir20/dozzle:latest
    logging:
      driver: local
      options:
        max-file: "5"
        max-size: 10m
    networks:
      dockernet: null
    restart: unless-stopped
networks:
  dockernet:
    name: dockernet
    external: true
```

### 🐛 Describe the bug / provide steps to reproduce it

When trying to run dozzle in agent mode it will not connect to the docker proxy specified in the env vars. I get this error:
```
{"level":"fatal","error":"error during connect: Get \"http://dockerproxy:2375/v1.48/info\": dial tcp: lookup dockerproxy on 127.0.0.11:53: no such host","time":"2025-02-22T15:55:12Z","message":"Could not create docker client"}
```

The intent is to connect to the docker-proxy I have running locally rather than map to docker.sock. If I remove the `agent` command it successfully connects to the docker-proxy.

Here is the compose for the docker-proxy I am using:
```
services:
  dockerproxy:
    container_name: dockerproxy
    environment:
      CONTAINERS: "1"
      INFO: "1"
      POST: "0"
    image: lscr.io/linuxserver/socket-proxy:latest
    logging:
      driver: local
      options:
        max-file: "5"
        max-size: 10m
    networks:
      dockernet: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: true
networks:
  dockernet:
    name: dockernet
    external: true
```

### 💻 Environment

Client: Docker Engine - Community
 Version:    27.5.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.33.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 13
  Running: 9
  Paused: 0
  Stopped: 4
 Images: 12
 Server Version: 27.5.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc version: v1.2.4-0-g6c52b3f
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-31-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 2.41GiB
 Name: racknerd-f37396
 ID: 2581dcab-7adb-4ab3-8551-5d811f5391a5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
