### ISSUE TITLE
OIDC Support

### ISSUE THREAD

**Issue by adrianipopescu** [amir20/dozzle#3675]
### Describe the feature you would like to see

Any chance we could have oidc support? That would allow us to plugin whatever centralized system we might have deployed.

This would be great for security inside the environments as many passwords = many potential weak points.

### Describe how you would like to see this feature implemented

Environment variables, preferably or entries in a config file

### Describe any alternatives you've considered

Alternatives would be a proxy for oidc, but it feels less than ideal as there's more points of failure.

**Comment by amir20** [comment]
My intention was to provide [proxy forward](https://dozzle.dev/guide/authentication#forward-proxy) solution so that anybody could integrate their own proxy. 

> Alternatives would be a proxy for oidc, but it feels less than ideal as there's more points of failure.

What do you mean by this? 

I don't think I'll have time to get to this personally. And not a lot of people are contributing to Dozzle so it feels like I would only prioritize this if a lot people ask for it.

**Comment by Woahai321** [comment]
i would like to 2nd this request please, oidc would be fab!

**Comment by anshibanov** [comment]
oidc would be great 🙏

**Comment by amir20** [comment]
I have worked on this a little https://github.com/amir20/dozzle/pull/3728

It's pretty complicated. So I wouldn't say it will be done soon. But it's a start.

**Comment by wollomatic** [comment]
Dozzle works great with [Oauth2-Proxy](https://github.com/oauth2-proxy/oauth2-proxy):

```
 oauth2proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.8.2
    restart: unless-stopped
    read_only: true
    mem_limit: 1G
    depends_on:
      - dozzle
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    command:
      - --upstream=http://dozzle:8080
      - --session-cookie-minimal=true
      - --allowed-role=admin,logviewer
    environment:
      # See: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/
      # and: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#keycloak-oidc-auth-provider
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:8080
      - OAUTH2_PROXY_PROVIDER=keycloak-oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=<<ISSUER_URL>>
      - OAUTH2_PROXY_REDIRECT_URL=<<REDIRECT_URL>>
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_CLIENT_ID=<<CLIENT_ID>>
      - OAUTH2_PROXY_CLIENT_SECRET # get from .env
      - OAUTH2_PROXY_CODE_CHALLENGE_METHOD=S256
      - OAUTH2_PROXY_OIDC_EXTRA_AUDIENCES=account
      - OAUTH2_PROXY_SCOPE=openid profile email
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_COOKIE_SECRET # get from .env
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_COOKIE_EXPIRE=10h
      - OAUTH2_PROXY_COOKIE_NAME=__Host-
      - OAUTH2_PROXY_COOKIE_SAMESITE=lax
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=false
      - OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER=false
      - OAUTH2_PROXY_PASS_BASIC_AUTH=true
      - OAUTH2_PROXY_PASS_USER_HEADERS=false
      - OAUTH2_PROXY_PASS_HOST_HEADER=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`l<<DOZZLE_URL>>`)"
      - "traefik.http.routers.dozzle.tls.certresolver=default"
      - "traefik.http.routers.dozzle.entrypoints=web-secure"
      - "traefik.http.routers.dozzle.middlewares=default-ratelimit@file, secHeaders@file" # depends on your Docker configuration
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
    networks:
      - traefik_proxy
      - dozzle
```
