### ISSUE TITLE
Freeze in change tab in chrome when leave from home page

### ISSUE THREAD

**Issue by webysther** [amir20/dozzle#3743]
### Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Agents

### Dozzle version

8.11.9

### ✅ Command used to run Dozzle

```yml
services:
  dozzle:
    image: ghcr.io/amir20/dozzle:v8
    container_name: app-log
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 512M
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - dozzle
    labels:
      wud.watch: false
    restart: unless-stopped

networks:
  dozzle:
    name: dozzle
```

### Describe the performance issue you are seeing

I have tested in the cognito mode in chrome and the problem still happens, I checked the console and everything looks ok, the freeze is brutal, I can even open the tab, I will keep monitoring to see if is related to some changes I made on my reverse proxy or here.

### How many containers, hosts, agents, etc. are you using?

4 agents
