### ISSUE TITLE
CPU Utilization Spikes on Node only when Dozzle is Running

### ISSUE THREAD

**Issue by mitchnemirov** [amir20/dozzle#3764]
### Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Swarm Mode

### Dozzle version

8.12.4

### ✅ Command used to run Dozzle

```
services:
  app:
    image: amir20/dozzle:latest
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.routers.dozzle.rule=Host(`logs.docker.domain`)
        - traefik.http.routers.dozzle.entrypoints=websecure
        - traefik.http.routers.dozzle.tls=true
        - traefik.http.routers.dozzle.tls.certresolver=letsencrypt
        - traefik.http.services.dozzle.loadbalancer.server.port=8080
    environment:
      - DOZZLE_MODE=swarm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
      - dozzle

networks:
  proxy:
    external: true
  dozzle:
    driver: overlay
```

### Describe the performance issue you are seeing

Possibly related to #3140 

Shortly after the Dozzle service starts up across all our nodes, CPU usage spikes on one of them (most likely the leader at that time). CPU usage grows until the node is basically unusable, and causes services running on the affected node to flatline and/or timeout. The only solution is to stop Dozzle, drain and restart the docker.socket service on the affected node, then bring the node back to active.

### How many containers, hosts, agents, etc. are you using?

We have three nodes running in Docker Swarm mode, with Dozzle running in swarm mode with deployment set to global. We have anywhere from 30-50 containers running at a time, and have recently cleaned up inactive images and containers.

**Comment by amir20** [comment]
I tested with 200 containers. Dozzle was running smoothly using about `~40MB`.  Can't say I can reproduce this. Will close if I don't hear anything.

**Comment by amir20** [comment]
That's strange. I would expect the Dozzle CPU usage to be high as well.

Enabling debug logs would be helpful. The only thing that could cause this issue is if you are running thousands of containers. However, I'll wait until you have debug enabled. I wonder if Dozzle is getting stuck in a loop, which could be overloading Docker.

**Comment by amir20** [comment]
Any update on this @mitchnemirov?

**Comment by mitchnemirov** [comment]
Hey @amir20, sorry for the delay. I was just able to test with debug mode on.

I cannot replicate the issue running Dozzle on a single node. See below for my compose:
```
services:
  app:
    image: amir20/dozzle:latest
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.routers.dozzle.rule=Host(`logs.docker.lvusd.org`)
        - traefik.http.routers.dozzle.entrypoints=websecure
        - traefik.http.routers.dozzle.tls=true
        - traefik.http.routers.dozzle.tls.certresolver=letsencrypt
        - traefik.http.services.dozzle.loadbalancer.server.port=8080
    environment:
      - DOZZLE_LEVEL=debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
```

With Swarm enabled, Dozzle worked just fine for ~10 minutes before one of our nodes had CPU usage spike and hold at over 100%. Once I stopped the Dozzle stack the only way to resolve the spike was to restart the docker and docker.socket systemd services.

Here is a gist link with the goroutines and heap: https://gist.github.com/mitchnemirov/6f08df0cf25870dbdacc609d711ceae1

Let me know if you need any other information. I also have the full goroutines debug stack saved in case that is required.
