### ISSUE TITLE
FR - dozzle-agent support rootless and/or read-only docker?

### ISSUE THREAD

**Issue by Herve-M** [amir20/dozzle#3767]
### Describe the feature you would like to see

It would be nice to follow Linux FHS and set temporary files under either `/tmp/dozzle/` or `/run/dozzle/` or `/var/run/dozzle/`.

Example of compose ansible template: 
```
services:
  dozzle:
    image: ghcr.io/amir20/dozzle:latest
    container_name: dozzle
    read_only: true
    user: "{{ dozzle_user.uid }}:{{ dozzle_user.group }}"
    group_add:
      - "{{ dozzle_user.group }}"
      - "{{ ansible_facts.getent_group["docker"][1] }}"
    restart: unless-stopped
    command: agent
    environment:
      - PUID={{ dozzle_user.uid }}
      - PGID={{ dozzle_user.group }}
      - DOZZLE_ENABLE_ACTIONS=false
      - DOZZLE_HOSTNAME={{ dozzle_agent_hostname }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - /tmp:uid={{ dozzle_user.uid }},gid={{ dozzle_user.group }},rw
    ports:
      - 7007:7007
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
```

Ends into this error:
```shell
dozzle  | {"level":"fatal","version":"v8.11.9","error":"failed to create temp file: open ./agent-3133852894.addr: permission denied","time":"2025-03-17T16:03:10Z","message":"Failed to run command"}
```

### Describe how you would like to see this feature implemented

Update https://github.com/amir20/dozzle/blob/9c2e03727b97e76d5e4e16013f96677e70e8aea7/internal/support/cli/agent_command.go#L40 to use OS's tempdir or have per OS adaption.
