### ISSUE TITLE
Error reading remote info: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by BriseBolt** [amir20/dozzle#3769]
### 🔍 Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Remote Hosts

### 📦 Dozzle version

8.12.4

### ✅ Command used to run Dozzle

Main instance
```
version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8003:8080
    environment:
      DOZZLE_ENABLE_ACTIONS: "true"
      DOZZLE_LEVEL: debug
      DOZZLE_REMOTE_HOST: tcp://192.168.0.110:8003
```

Instance I am trying to connect to
```
version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8003:8080
    environment:
      DOZZLE_ENABLE_ACTIONS: "true"
      DOZZLE_LEVEL: debug
```

### 🐛 Describe the bug / provide steps to reproduce it

Start two instances on two different machines on the same local network, and try to connect to the other from only one instance

### 💻 Environment

Client: Docker Engine - Community
 Version:    28.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.22.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.34.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 28.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-32-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 953.8MiB
 Name: debian12-mod
 ID: da1ddeaf-af26-44d8-b1f5-d502fbb3e449
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false

### 📜 If applicable, attach your Dozzle logs. You many need to enable debug mode. See https://dozzle.dev/guide/debugging.

    level=infoversion=v8.12.4time=2025-04-08T11:30:09Zmessage=Dozzle version v8.12.4

    level=infoversion=v8.12.4time=2025-04-08T11:30:09Zmessage=Consider using Dozzle's remote agent to manage remote hosts. See https://dozzle.dev/guide/agent for more information

    level=debugversion=v8.12.4time=2025-04-08T11:30:09Zmessage=Remote host certificate path does not exist /certs/192.168.0.110, falling back to default: /certs

    level=infoversion=v8.12.4host.available=falsehost.dockerVersion=host.endpoint=tcp://192.168.0.110:8003host.id=tcp:192.168.0.110:8003host.memTotal=0host.nCPU=0host.name=192.168.0.110host.type=time=2025-04-08T11:30:09Zmessage=Adding remote host

    level=debugversion=v8.12.4time=2025-04-08T11:30:09Zmessage=Not using TLS for remote client

    level=errorversion=v8.12.4error=Error reading remote info: invalid character '<' looking for beginning of valuetime=2025-04-08T11:30:09Zmessage=Failed to get docker info

    level=debugversion=v8.12.4host=192.168.0.110time=2025-04-08T11:30:09Zmessage=Listing containers

    level=warnversion=v8.12.4error=invalid character '<' looking for beginning of valuehost.available=falsehost.dockerVersion=host.endpoint=tcp://192.168.0.110:8003host.id=tcp:192.168.0.110:8003host.memTotal=0host.nCPU=0host.name=192.168.0.110host.type=time=2025-04-08T11:30:09Zmessage=Could not connect to remote host

    level=debugversion=v8.12.4host=debian12-modtime=2025-04-08T11:30:09Zmessage=Listing containers

    level=debugversion=v8.12.4time=2025-04-08T11:30:09Zmessage=Adding local Docker Engine

    level=debugversion=v8.12.4host=debian12-modtime=2025-04-08T11:30:09Zmessage=Fetching host
