### ISSUE TITLE
Hamburger menu padding within notification bar

### ISSUE THREAD

**Issue by ShanaryS** [amir20/dozzle#3823]
### 🔍 Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

v8.12.5+

### ✅ Command used to run Dozzle

 ```
 dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_ENABLE_ACTIONS=True
      - DOZZLE_ENABLE_SHELL=True
      - DOZZLE_ADDR=:8888
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${DOCKER_TIMEZONE}
    volumes:
      - ${DOCKER_CONFIGS}/dozzle:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8888
    extra_hosts:
      - ${DOCKER_HOSTNAME}
    restart: unless-stopped
    pull_policy: always
```

### 🐛 Describe the bug / provide steps to reproduce it

Open dozzle on Iphone 15 Pro Max as PWA (works in browser), the hamburger menu and others are pushed up to the notification bar, does not register touches. I'm fairly certain this bug was introduced in #3765.

On a separate note, the red-blue menu for the containers, that allows you to stop/start, doesn't show up in portrait mode. Further, when I open it in landscape mode, I check/uncheck all the levels since the menu isn't scrollable and it's off screen (seems to work if logs don't fill the screen).

### 💻 Environment

```
Client: Docker Engine - Community
 Version:    28.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.21.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.33.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 50
  Running: 47
  Paused: 0
  Stopped: 3
 Images: 33
 Server Version: 28.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc version: v1.2.4-0-g6c52b3f
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.19.0-40-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 31.22GiB
 Name: icycool
 ID: 1b01b39e-0b69-4526-b7b4-d9a8bf502985
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: everybody
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### 📜 Dozzle logs are required for debugging purposes. You may need to enable debug mode. See https://dozzle.dev/guide/debugging.

None

### 📸 If applicable, add screenshots to help explain your bug

This first one is for the padding of the hamburger menu:
![Image](https://github.com/user-attachments/assets/50c5e869-ae31-473e-9ff5-804dc35cc6fe)

This second one is to show some items are inaccessible in the dropdown:
![Image](https://github.com/user-attachments/assets/65b6bf0b-8729-4fe1-af0d-9cf39c2b4d27)
