### ISSUE TITLE
A problem with quotes when searching

### ISSUE THREAD

**Issue by pikhovkin** [amir20/dozzle#3831]
### 🔍 Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Remote Hosts

### 📦 Dozzle version

8.12.10

### ✅ Command used to run Dozzle

```yaml
services:
  dozzle:
    image: amir20/dozzle:v8.12.10
    expose:
      - 8080
    volumes:
        - ./data:/data
    environment:
      DOZZLE_ENABLE_ACTIONS: false
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_AUTH_TTL: 8h
      DOZZLE_REMOTE_AGENT: "my-agent-domain:7007"
```

### 🐛 Describe the bug / provide steps to reproduce it
image1

![Image](https://github.com/user-attachments/assets/0019eac3-7cb3-41da-8ef6-b8cc657674b9)

image2

![Image](https://github.com/user-attachments/assets/148c9631-6961-491d-99c3-6de573e5dc3d)

image3

![Image](https://github.com/user-attachments/assets/b15afda7-7ff4-4e3a-bd46-a5dff607b5d5)

### 💻 Environment

```
Client: Docker Engine - Community
 Version:    28.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.22.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.34.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Server Version: 28.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-136-generic
 Operating System: Linux Mint 21
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.66GiB
 ID: 5HTG:QRWB:3WZT:PQLN:Z2UQ:YJYB:PJA2:LR6E:JQGY:GHWA:X35B:QBF6
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### 📜 Dozzle logs are required for debugging purposes. You may need to enable debug mode. See https://dozzle.dev/guide/debugging.

...
