### ISSUE TITLE
dozzle-from-file with multiple .log files?

### ISSUE THREAD

**Issue by meiersmarkus** [amir20/dozzle#3835]
### Describe the feature you would like to see

It would be great if you could create multiple dozzle-from-file containers in the docker-compose and then display them separately in dozzle.

### Describe how you would like to see this feature implemented
```
  dozzle-from-file:
    container_name: Logfile
    image: alpine
    volumes:
      - /volume1/docker/dozzle/Logfile.log:/var/log/stream.log
    command:
      - tail
      - -f
      - /var/log/stream.log
    network_mode: none
    restart: unless-stopped

  dozzle-from-file2:
    container_name: Logfile2
    image: alpine
    volumes:
      - /volume1/docker/dozzle/Logfile2.log:/var/log/stream2.log
    command:
      - tail
      - -f
      - /var/log/stream2.log
    network_mode: none
    restart: unless-stopped
    labels:
```
