### ISSUE TITLE
Resource calculation problem

### ISSUE THREAD

**Issue by vanodevium** [amir20/dozzle#3836]
### 🔍 Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

v8.12.10

### ✅ Command used to run Dozzle

```yml
name: "dozzle"

services:

  dozzle:
    image: "amir20/dozzle:latest"
    restart: unless-stopped
    env_file: .env
    environment:
      - "DOZZLE_AUTH_PROVIDER=simple"
      - "DOZZLE_NO_ANALYTICS=true"
      - "DOZZLE_LEVEL=error"
    volumes:
      - "./.data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.dozzle.rule=Host(`${HOST}`)"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"

networks:
  traefik:
    name: "traefik"
    external: true
```

### 🐛 Describe the bug / provide steps to reproduce it

![Image](https://github.com/user-attachments/assets/b4e1d742-cdd2-43f5-bbdd-b2219031fb37)

All is fine but this server has 1 CPU and 2GB RAM.
This problem is when I open merged view for containers.

### 💻 Environment

Client: Docker Engine - Community
 Version:    26.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 51
  Running: 51
  Paused: 0
  Stopped: 0
 Images: 319
 Server Version: 26.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-87-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.566GiB
 Name: integration
 ID: 2078e4ae-7ce0-49d9-825c-766641a5c23c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

### 📜 Dozzle logs are required for debugging purposes. You may need to enable debug mode. See https://dozzle.dev/guide/debugging.

No logs. This is UI problem.
