### ISSUE TITLE
Containers no longer visibles on docker-compose install in socket-proxy mode.

### ISSUE THREAD

**Issue by ildyria** [amir20/dozzle#3887]
### 🔍 Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

Broken from version 8.10.6 (see checks)

### ✅ Command used to run Dozzle

docker compose:
```yaml
services:
  dozzle:
    # image: amir20/dozzle:v6.5.2 # make sure you use the most recent version
    # image: amir20/dozzle:v8.10.5 # make sure you use the most recent version
    image: amir20/dozzle:v8.12.15 # make sure you use the most recent version
    container_name: Dozzle
    user: 65534:65534
    read_only: true
    mem_limit: 256M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    depends_on:
      - dockerproxy
    environment:
      DOZZLE_NO_ANALYTICS: true
      DOZZLE_REMOTE_HOST: tcp://dockerproxy:2375
      DOZZLE_AUTH_PROVIDER: forward-proxy
    networks:
      - docker-proxynet
      - traefik-servicenet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.${DOMAIN_NAME1}`)"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.routers.dozzle.tls.certresolver=myresolver"
      - "traefik.http.routers.dozzle.middlewares=chain-basic-authelia@file"
```

Socket proxy:
```yaml
services:
  dockerproxy:
    container_name: Private-docker-proxy
    image: wollomatic/socket-proxy:1
    security_opt:
      - no-new-privileges
    command:
      # with this configuration socket-proxy acts similar to the tecnativa proxy.
      # For additional hardening please refer to the documentation of the wollomatic/socket-proxy image
      - '-loglevel=info' # set to debug for far more logging
      - '-allowfrom=${SOCKET_PROXY_ALLOW_FROM}'
      - '-listenip=0.0.0.0'
      - '-allowGET=/v1\..{1,2}/(version|containers/.*|events.*)|/_ping' # this regexp allows readonly access only for requests that traefik needs
      - '-allowHEAD=/_ping'
      - '-shutdowngracetime=5'
      - '-watchdoginterval=600'
      - '-stoponwatchdog'
    restart: unless-stopped
    read_only: true
    mem_limit: 64M
    cap_drop:
      - ALL
    user: 65534:994 # replace <<docker-gid>> (994) with the docker gid on your host system.
                    # $ getent group docker
                    # docker:x:994:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-proxynet
```

Traefik:
```yaml
# Inspired from https://github.com/wollomatic/traefik-hardened 
services:
  reverse-proxy:
    image: traefik:v3
    container_name: Traefik
    # read_only: true
    ports:
      - 80:80 # The HTTP port
      - 443:443 # The HTTPS port
      # The Web UI port (enabled by --api.insecure=true)
      # - 48080:8080
      - 35730:35730
    depends_on:
      - dockerproxy
    security_opt:
      - no-new-privileges:true
    networks:
      - docker-proxynet
      - traefik-servicenet
    volumes:
      # So that traefik can listen to docker events
      - $DOCKERDIR/app_data/traefik/letsencrypt:/letsencrypt
      - $DOCKERDIR/app_data/traefik/logs/:/var/log/
      - $DOCKERDIR/app_data/traefik/plugins/:/opt/traefik/plugins-storage/sources
      # Configuration
      - $DOCKERDIR/app_data/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - $DOCKERDIR/app_data/traefik/dynamic:/etc/traefik/dynamic
      - $DOCKERDIR/app_data/traefik/authusers.txt:/etc/traefik/authusers.txt:ro  # userfile for basic auth
      - $DOCKERDIR/app_data/plugins/:/plugins-local/src/
    environment:
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME1}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.middlewares=chain-basic-authelia@file"
```
Base docker compose:
```yaml
########################### SECRETS
secrets:
  authelia_jwt_secret:
    file: $DOCKERDIR/secrets/authelia_jwt_secret
  authelia_session_secret:
    file: $DOCKERDIR/secrets/authelia_session_secret
  authelia_storage_encryption_key:
    file: $DOCKERDIR/secrets/authelia_storage_encryption_key
  authelia_session_redis_password:
    file: $DOCKERDIR/secrets/authelia_session_redis_password
  authelia_smtp_secret:
    file: $DOCKERDIR/secrets/authelia_smtp_secret

########################### NETWORKS
networks:
  # Secure proxy. Do not expose to internet
  docker-proxynet:
    name: docker-proxynet
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.90.0/24

  # traefik service net (internal network to reverse proxy)
  traefik-servicenet:
    name: traefik-servicenet
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24

include:
  ########################### SERVICES
  # CORE
  - compose/socket-proxy.yml
  - compose/traefik.yml
  - compose/authelia.yml
  - compose/monitoring/prometheus.yml
  - compose/monitoring/grafana.yml
  - compose/monitoring/gatus.yml
  - compose/monitoring/dozzle.yml
```

### 🐛 Describe the bug / provide steps to reproduce it

I updated from v6 to latest, and was suprised to discover that the list of container on the left was broken. By dichotomy I found out which version was breaking:
v8.0.1: ✅ 
v8.5.0: ✅ 
v8.10.0: ✅ 
v8.11.0: ❌ 
v8.10.7: ❌ 
**v8.10.6**: ✅ 
v8.10.5: ✅ 

![Image](https://github.com/user-attachments/assets/28cb836f-df20-4f84-bab8-aa7c565164d3) (same image on 8.10.6)

![Image](https://github.com/user-attachments/assets/a3c9b6e2-36f0-4572-96b1-522cf3549f11)
(clicking on dockerproxy does not do anything)

On version 8.12.15 it is worse:
![Image](https://github.com/user-attachments/assets/eb38434e-1ac5-447f-9ca7-bb1b0f058189)
Notice the csp error (that is new).

When clicking on Dozzle container for example:
![Image](https://github.com/user-attachments/assets/8132ce12-19be-4e54-8914-f37658052738)

Note that when switching to the Custom groups view, it is now possible to open the groups and get some access to the logs:
![Image](https://github.com/user-attachments/assets/24cc5126-de8b-40b8-b054-b94ccb281b5b)

### 💻 Environment

```
Client: Docker Engine - Community
 Version:    28.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.21.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.33.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 52
  Running: 41
  Paused: 0
  Stopped: 11
 Images: 209
 Server Version: 28.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc version: v1.2.4-0-g6c52b3f
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-30-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.04GiB
 Name: ns3130454
 ID: a6a8ec33-c918-4e5e-84e0-df88fa60b219
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### 📜 Dozzle logs are required for debugging purposes. You may need to enable debug mode. See https://dozzle.dev/guide/debugging.

This looks like a front-end issue to me more than backend.

### 📸 If applicable, add screenshots to help explain your bug

See screenshots above :)

**Comment by amir20** [comment]
First, I would try without using socket proxy. Does it work? If it does then something is broken with your proxy and I wouldn't be able to help. There are so many different types of proxies which is outside of my scope to support. 

I do know that you need to setup `info` API as documented at https://dozzle.dev/guide/remote-hosts#connecting-with-a-socket-proxy. 

Second, the CSP error is because something is trying to load a resource at `https://authelia...` I don't know what that is. I would look into it. 

Third, at the very least I would expect the logs to work because that hasn't changed much recently.  Again, does it work without a proxy? If so, probably something on your side.

**Comment by ildyria** [comment]
Hi, thanks for the quick reply and thank you for the pointer. I tried to look for breaking changes, but I did not see those.
I will double check and come back at you. :) I still find it surprising that it breaks from a patch version bump (8.10.6 => 8.10.7).

**Comment by ildyria** [comment]
Okay so issue _"fixed"_.

![Image](https://github.com/user-attachments/assets/307d4ddb-3071-4399-96c4-eb27ab77ae04)

**I switched to using agent mode.** Not so happy about it because it increases my socket exposure surface, but at least it works. Bellow is my updated docker compose file, noticed the internal network between the agent and the exposed container.

```yaml
services:
  dozzle-agent:
    container_name: Dozzle-Agent
    image: amir20/dozzle:latest
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
    networks:
      - dozzle-net

  dozzle:
    image: amir20/dozzle:latest
    container_name: Dozzle
    user: 65534:65534
    read_only: true
    mem_limit: 256M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    depends_on:
      - dozzle-agent
    environment:
      DOZZLE_NO_ANALYTICS: true
      DOZZLE_REMOTE_AGENT: dozzle-agent:7007
      DOZZLE_AUTH_PROVIDER: forward-proxy
      INFO: 1
      CONTAINERS: 1
    networks:
      - traefik-servicenet
      - dozzle-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.${DOMAIN_NAME1}`)"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.routers.dozzle.tls.certresolver=myresolver"
      - "traefik.http.routers.dozzle.middlewares=chain-basic-authelia@file"

networks:
  dozzle-net:
    internal: true
```

Also worth to be mentioned, on https://dozzle.dev/guide/agent the docker compose given are examples are :
```yaml
services:
  dozzle-agent:
    image: amir20/dozzle:latest
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
```
and 
```yaml
services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_REMOTE_AGENT=agent:7007
    ports:
      - 8080:8080 # Dozzle UI port
```

`- DOZZLE_REMOTE_AGENT=agent:7007` should be `- DOZZLE_REMOTE_AGENT=dozzle-agent:7007`

👍
