### ISSUE TITLE
Dozzle agent can't display the detail right window when row pressed.

### ISSUE THREAD

**Issue by C8opmBM** [amir20/dozzle#3934]
### 🔍 Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Agents

### 📦 Dozzle version

v8.12.18

### ✅ Command used to run Dozzle

Hello, 
I noticed that on my 2 nodes (1 raspberry pi home and a vps for pangolin rented) the dozzle agents cannot read the detailed log when a row is clicked.

Is this the normal behaviour? On the main, non agent dozzle, the logs expand correctly. 
I attach a screen to show the issue.

### 🐛 Describe the bug / provide steps to reproduce it

see above

### 💻 Environment

Client: Docker Engine - Community
 Version:    28.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.35.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 19
  Running: 17
  Paused: 0
  Stopped: 2
 Images: 25
 Server Version: 28.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.21-v8+
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.705GiB
 Name: rpi
 ID: 6SJJ:H3B7:W6YN:SFZA:RRMM:DDT6:A3KA:PQBY:7OTI:GTVJ:72CF:EWOF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false

### 📜 Dozzle logs are required for debugging purposes. You may need to enable debug mode. See https://dozzle.dev/guide/debugging.

level=
info
version=
v8.12.18
time=
2025-05-30T12:46:58Z
message=
Dozzle version v8.12.18
level=
info
version=
v8.12.18
clients=
3
time=
2025-05-30T12:46:58Z
message=
Connected to Docker
level=
info
version=
v8.12.18
time=
2025-05-30T12:46:58Z
message=
Accepting connections on :8080

### 📸 If applicable, add screenshots to help explain your bug

![Image](https://github.com/user-attachments/assets/fa7aee90-77b4-46b2-a1ff-f972ba6f6b06)
![Image](https://github.com/user-attachments/assets/4d93da41-b293-478b-b244-db298a711637)

**Comment by C8opmBM** [comment]
My docker compose:

```
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    profiles:
      - monitor
    networks:
      - net
    environment:
      DOZZLE_REMOTE_AGENT: 192.168.1.150:53373,77.90.45.153:7007
      DOZZLE_HOSTNAME: proxmox
      DOZZLE_NO_ANALYTICS: true
      DOZZLE_ENABLE_ACTIONS: true
      #DOZZLE_AUTH_PROVIDER: forward-proxy
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
```

```
  dozzle-agent:
    container_name: dozzle-agent
    image: amir20/dozzle:latest
    command: agent
    profiles:
      - monitor
    networks:
      - monitor
    ports:
      - 53373:7007
    environment:
      DOZZLE_HOSTNAME: rPi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
```
