### ISSUE TITLE
Healthchesk start failing after some time

### ISSUE THREAD

**Issue by DobriyDed** [amir20/dozzle#3942]
### 🔍 Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Agents

### 📦 Dozzle version

 v8.12.20

### ✅ Command used to run Dozzle

```services:
  dozzle-agent:
    image: amir20/dozzle:latest
    command: agent
    environment:
      - DOZZLE_HOSTNAME=GPU-4060ti
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7171:7007
    restart: always
```

### 🐛 Describe the bug / provide steps to reproduce it

1. Container mistakenly (?) listening port 8080 in **AGENT** mode
2. 
```
CONTAINER ID   NAMES                   PORTS                                                     CREATED         STATUS
f92b279c0e75   dozzle-dozzle-agent-1   8080/tcp, 0.0.0.0:7171->7007/tcp, [::]:7171->7007/tcp     2 seconds ago   Up 2 seconds (health: starting)
```  
 
3. If system allready have other container on port 8080, **AFTER SOME TIME** healthcheck start to failing, truying to connect 8080 instead of configured (port 7171)  in docker compose 
 

5. `{"level":"info","version":"v8.12.20","address":":8080","base":"/","time":"2025-06-02T13:14:23Z","mess                       age":"Making HTTP request to server"}
{"level":"info","version":"v8.12.20","url":"http://localhost:8080/healthcheck","time":"2025-06-02T13:                       14:23Z","message":"performing healthcheck"}
{"level":"fatal","version":"v8.12.20","error":"Get \"http://localhost:8080/healthcheck\": dial tcp [:                       :1]:8080: connect: connection refused","time":"2025-06-02T13:14:23Z","message":"Failed to run command                       "}
`

### 💻 Environment

Docker (latest) Version:    28.2.2
buildx: Docker Buildx (Docker Inc.)    Version:  v0.24.0
compose: Docker Compose (Docker Inc.)   Version:  v2.36.2

Ubuntu 22
 Kernel Version: 5.15.0-140-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.46GiB

### 📜 Dozzle logs are required for debugging purposes. You may need to enable debug mode. See https://dozzle.dev/guide/debugging.

dozzle-agent-1  | {"level":"info","version":"v8.12.20","time":"2025-06-02T13:50:27Z","message":"Dozzle agent version v8.12.20"}
dozzle-agent-1  | {"level":"info","version":"v8.12.20","time":"2025-06-02T13:50:27Z","message":"Agent listening on [::]:7007"}
dozzle-agent-1  | {"level":"info","version":"v8.12.20","time":"2025-06-02T14:00:05Z","message":"Dozzle agent version v8.12.20"}
dozzle-agent-1  | {"level":"info","version":"v8.12.20","time":"2025-06-02T14:00:05Z","message":"Agent listening on [::]:7007"}

**Comment by amir20** [comment]
Hm I wonder if I broke something. I'll test it locally to see if I can reproduce.

**Comment by amir20** [comment]
Hi @DobriyDed , 

I wasn't able to reproduce this. I used 

```
services:
  dozzle-agent:
    image: amir20/dozzle:latest
    command: agent
    environment:
      - DOZZLE_LEVEL=debug
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"

```

`docker ps` shows just fine after multiple times 

<img width="1382" alt="Image" src="https://github.com/user-attachments/assets/19f73467-3ec5-4783-a296-323fdb18bf88" />

Reading your comment again, I think you might be misunderstanding how containers work. The ports are internal for health checking.  Changing them will have no affect on the command. In your example `7171` is the _external_ port which to the container doesn't matter. 

Closing since this is probably something happening on your side.
