### ISSUE TITLE
Cant view old logs for stack

### ISSUE THREAD

**Issue by iLuckyW** [amir20/dozzle#3955]
### 🔍 Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Swarm Mode

### 📦 Dozzle version

8.12.21

### ✅ Command used to run Dozzle

```
version: "3.2"
services:
  dozzle:
    image: amir20/dozzle:v8.12.21
    environment:
      DOZZLE_MODE: swarm
      DOZZLE_AUTH_PROVIDER: forward-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      labels:
        traefik.enable: 'true'
        traefik.docker.network: traefik_backend
        traefik.http.routers.router-dozzle.rule: Host(`dozzle.${LOCAL_DOMAIN}`)
        traefik.http.routers.router-dozzle.entrypoints: websecure
        traefik.http.routers.router-dozzle.middlewares: authelia # auth middleware
        traefik.http.services.service-dozzle.loadBalancer.server.port: '8080'
    networks:
      - traefik_backend
      - socket-proxy
networks:
  traefik_backend:
    external: true
  socket-proxy:
    external: true
```

### 🐛 Describe the bug / provide steps to reproduce it

When trying to scroll up in the logs for a stack (e. g. /stack/duplicacy) there a no more logs displayed, and the page just loads forever. Though, when viewing the container of that stack separately (e. g. /container/fd3cecc7c2c3) I am able to view all logs.

### 💻 Environment

Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 27
  Running: 25
  Paused: 0
  Stopped: 2
 Images: 26
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: active
  NodeID: m06d10ibq3d5zkatfl1fsgasi
  Is Manager: true
  ClusterID: nxbburcb5wmoa05im5tfe3p2e
  Managers: 3
  Nodes: 3
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.178.241
  Manager Addresses:
   192.168.178.133:2377
   192.168.178.202:2377
   192.168.178.241:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.12-1-pve
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 18.84GiB
 Name: swarm-01
 ID: c840978d-3c22-4058-95d8-e92775c3fb13
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

### 📜 Dozzle logs are required for debugging purposes. You may need to enable debug mode. See https://dozzle.dev/guide/debugging.

no specific logs I could find, this happens for all stacks
