### ISSUE TITLE
Webpage crashes when highlighting logs

### ISSUE THREAD

**Issue by ShanaryS** [amir20/dozzle#3980]
### 🔍 Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

8.13.0

### ✅ Command used to run Dozzle

  ```
dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_ENABLE_ACTIONS=True
      - DOZZLE_ENABLE_SHELL=True
      - DOZZLE_ADDR=:8888
    volumes:
      - ${DOCKER_CONFIGS}/dozzle:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8888
    restart: unless-stopped
    pull_policy: always
```

### 🐛 Describe the bug / provide steps to reproduce it

Highlighting the start of a log line crashes the webpage. Reloading fixes it. This is both in browser and PWA.

This ONLY happens on v8.13.0 and ONLY happens in Chrome, nothing happens in Firefox.

### 💻 Environment

```
Client: Docker Engine - Community
 Version:    28.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.21.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.33.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 47
  Running: 45
  Paused: 0
  Stopped: 2
 Images: 42
 Server Version: 28.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc version: v1.2.4-0-g6c52b3f
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.19.0-40-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 31.22GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### 📜 Dozzle logs are required for debugging purposes. You may need to enable debug mode. See https://dozzle.dev/guide/debugging.

Logs are visible in the video, I also tried with debug on and there doesn't seem to be anything extra.

### 📸 If applicable, add screenshots to help explain your bug

https://github.com/user-attachments/assets/bd5be1cc-18cc-4bf6-84e6-a519666b1b94
