### ISSUE TITLE
🚨 Expired TLS certificate [fixed]

### ISSUE THREAD

**Issue by nwerosama** [amir20/dozzle#4008]
### 🔍 Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Agents

### 📦 Dozzle version

v8.13.2

### ✅ Command used to run Dozzle

```yml
services:
  dozzle:
    image: amir20/dozzle:latest
    command: agent
    container_name: dozzle-agent
    restart: unless-stopped
    environment:
      DOZZLE_HOSTNAME: clover
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7007:7007
```

### 🐛 Describe the bug / provide steps to reproduce it

The Dozzle host that publicly shows logs from connected agents started reporting that two of my agents is displaying expired certificate errors.
Upon checking the agent's endpoint in browser, it shows that the container's self-signed certificate had expired as of today.

It was originally on v8.13.1, updating to latest did not work.

### 💻 Environment

```
Client:
 Version:    28.3.0
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.37.3
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 11
  Paused: 0
  Stopped: 0
 Images: 14
 Server Version: 28.3.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c787fb98911740dd3ff2d0e45ce88cdf01410486.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.15.3-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.779GiB
 Name: clover
 ID: f2b55c8d-3d7a-41da-9ba0-b108a3db646d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### 📜 Dozzle logs are required for debugging purposes. You may need to enable debug mode. See https://dozzle.dev/guide/debugging.

level=warn
version=v8.13.2
error=rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: remote error: tls: expired certificate"
host=clover
time=2025-06-27T03:20:57Z
message=error fetching host info for client
