### ISSUE TITLE
log field not renderred when there is a field valued null

### ISSUE THREAD

**Issue by wey-gu** [amir20/dozzle#4013]
### 🔍 Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

v8.13.3

### ✅ Command used to run Dozzle

with compose

```yaml
---
services:
  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    security_opt:
      - seccomp=unconfined
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_NO_ANALYTICS=true
      - DOZZLE_BASE=/dozzle
```

### 🐛 Describe the bug / provide steps to reproduce it

For json/structured logs, i noticed when there is a field(named span_id, not sure if key matters), valued (null), all the log lines(json lines) will be rendered as empty, when de-select that field from details, json log lines will show!

### 💻 Environment

```
Client: Docker Engine - Community
 Version:    28.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.35.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 28.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-138-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
```

### 📜 Dozzle logs are required for debugging purposes. You may need to enable debug mode. See https://dozzle.dev/guide/debugging.

```
{
  "level": "warn",
  "version": "v8.13.1",
  "type": "<nil>",
  "time": "2025-06-30T03:06:43Z",
  "message": "unknown logEvent type"
}
```

### 📸 If applicable, add screenshots to help explain your bug

see:

<img width="1537" alt="Image" src="https://github.com/user-attachments/assets/cecd410c-b83e-4f57-9777-123a49a79847" />
<img width="1534" alt="Image" src="https://github.com/user-attachments/assets/b07ed144-dace-448e-b47c-e6faad319a70" />
