### ISSUE TITLE
docker-compose?

### ISSUE THREAD

**Issue by thepenguinthatwants** [amir20/dozzle#77]
Can you write a docker-compose version of this?

**Comment by amir20** [comment]
I won't have time this week. Maybe someone else will. But I recommend using the service with [swarm](https://github.com/amir20/dozzle#docker-swarm-deploy) if you need it to always be up with healthchecks.

**Comment by adamzero1** [comment]
@thepenguinthatwants something like this should work (it's what I have been using locally)
``` yml
version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_TAILSIZE=100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
```
