### ISSUE TITLE
Restrict To Specific Containers

### ISSUE THREAD

**Issue by adamzero1** [amir20/dozzle#83]
I'm wondering if it would be possible to restrict the list of availble containers?
E.g 1 host with 2 projects, would be good if you could restict to only show containers from 1 project

**Comment by amir20** [comment]
Hmm...It's not possible right now. But I could add it. What's your use case? Is it that important to hide other containers for you?

**Comment by adamzero1** [comment]
Thanks for getting back so quick!
I was hoping to use/include this with [mdoq](https://www.mdoq.io) the premise being there could be multiple projects on a single server. With the app mounting the `docker.sock` it can obviously see everything. Which is not ideal, as we need to keep seperation between projects.
It's something I'm happy to add and create a PR for, if you could provide some build steps so I can test locally before creating the PR?

**Comment by amir20** [comment]
Nice. That would be a good addition to mdoq. 

It would be really nice to get a PR. I am really busy at work so won't have much time to work on this until next week. But I can review and merge.  

Here are some things that might get you going with **building** Dozzle: 
1. Install nodejs v12
2. Install go v1.12.7
3. Do `go get -u github.com/gobuffalo/packr/packr`
4. `npm i` to install node mods
5. You can look at the [automated build file](https://github.com/amir20/dozzle/blob/master/.github/goreleaser/Dockerfile) script to understand how I build everything. 
6. `npm start` should automatically do `go mod download` and start dozzle at port localhost:8080

Here is what you would need to change: 
1. Add a new string flag that can be configure the regex (or whatever you decide to do) at https://github.com/amir20/dozzle/blob/master/main.go#L38
2. Possibly add the logic at https://github.com/amir20/dozzle/blob/master/main.go#L135 to filter based on the flag. 
3. If it's important, then you would need to also update https://github.com/amir20/dozzle/blob/master/main.go#L148 to not allow logs of filtered docker images

I hope this helps. Let me know if you have any questions.

**Comment by adamzero1** [comment]
Nice one, [PR raised](https://github.com/amir20/dozzle/pull/84)

**Comment by amir20** [comment]
Should be fixed in https://github.com/amir20/dozzle/pull/85

**Comment by amir20** [comment]
@adamzero1 Released v1.12 can you try it out?

**Comment by adamzero1** [comment]
@amir20 looks to be working
``` yml
version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_CONTAINERRESTRICTIONS=6893-.*
      - DOZZLE_TAILSIZE=100
      - DOZZLE_FILTERNAME=6893-.*
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
```
Only issue is we have now lost the ability to pass in any other kind of filter. We are forced to filter on name. I had thought you wanted it more generic. where you could pass in something like:  
``` yml
DOZZLE_FILTERNAME=name=6893-.*
```
It still works for what I need though, nice one!
