### ISSUE TITLE
Listen tcp: address 8888: missing port in address

### ISSUE THREAD

**Issue by averri** [amir20/dozzle#887]
**Describe the bug**
Dozzle is reporting an error when there is nothing wrong with the configuration.

**To Reproduce**
Run the Dozzle container attaching its network to the network of another container. See example below.

```yml
version: "3"

services:

    # Other services...

    dozzle:
    image: amir20/dozzle:v3.0.3
    container_name: dozzle
    environment:
      - DOZZLE_ADDR=8888
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
```

**Expected behavior**
Dozzle should allow starting the Docker container without specifying the `ports` attribute.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Docker version [e.g. `docker version`'s output]
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:54:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:52:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```
 - Browser & version [e.g. chrome, safari]
 - Version [e.g. 1.26.1. Can be found at `<Dozzle-host>/version`]

**If applicable include logs with `--level debug` and browser logs**

```logs
dozzle       | level=info msg="Dozzle version v3.0.3"
dozzle       | level=info msg="Accepting connections on 8888"
dozzle       | level=fatal msg="listen tcp: address 8888: missing port in address"
```
